name: Setup gotools
runs:
  using: "composite"
  steps:
    - name: Install gotools
      shell: bash
      run: |
        make setup/gotools

    - name: Fix PATH
      shell: bash
      run: |
        echo "${HOME}/go/bin" >> ${GITHUB_PATH}
