// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: access.sql

package db

import (
	"context"
	"database/sql"
)

const listPathAccessForUser = `-- name: ListPathAccessForUser :many
SELECT
    device_serial,
    rel_path,
    level
FROM
    path_access
WHERE
    path_access.user_id = ?1
    OR path_access.group_id IN (
        SELECT
            group_id
        FROM
            group_members
        WHERE
            group_members.user_id = ?1
    )
    OR path_access.group_id IN (
        SELECT
            id
        FROM
            groups
        WHERE
            name = 'everyone'
            AND builtin = 1
    )
`

type ListPathAccessForUserRow struct {
	DeviceSerial string
	RelPath      string
	Level        string
}

// ListPathAccessForUser returns every row that applies to a user: their own,
// their groups', and the built-in everyone group's. accessutil resolves
// ancestors in memory from this one read.
func (q *Queries) ListPathAccessForUser(ctx context.Context, userID sql.NullInt64) ([]ListPathAccessForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listPathAccessForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPathAccessForUserRow
	for rows.Next() {
		var i ListPathAccessForUserRow
		if err := rows.Scan(&i.DeviceSerial, &i.RelPath, &i.Level); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserPathAccess = `-- name: SetUserPathAccess :exec
INSERT INTO
    path_access (device_serial, rel_path, user_id, level)
VALUES
    (?, ?, ?, ?) ON CONFLICT (user_id, device_serial, rel_path)
WHERE
    user_id IS NOT NULL DO
UPDATE
SET
    level = excluded.level
`

type SetUserPathAccessParams struct {
	DeviceSerial string
	RelPath      string
	UserID       sql.NullInt64
	Level        string
}

// SetUserPathAccess grants a user a level on a path, replacing the level any
// earlier grant to that user on that path carried.
func (q *Queries) SetUserPathAccess(ctx context.Context, arg SetUserPathAccessParams) error {
	_, err := q.db.ExecContext(ctx, setUserPathAccess,
		arg.DeviceSerial,
		arg.RelPath,
		arg.UserID,
		arg.Level,
	)
	return err
}
