// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: access.sql

package db

import (
	"context"
	"database/sql"
)

const deletePathAccessTree = `-- name: DeletePathAccessTree :execrows
DELETE FROM path_access
WHERE
    device_serial = ?1
    AND (
        rel_path = ?2
        OR substr(rel_path, 1, length(?2) + 1) = ?2 || '/'
    )
`

type DeletePathAccessTreeParams struct {
	DeviceSerial string
	RelPath      string
}

// DeletePathAccessTree drops the rows on a path and everything beneath it.
func (q *Queries) DeletePathAccessTree(ctx context.Context, arg DeletePathAccessTreeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deletePathAccessTree, arg.DeviceSerial, arg.RelPath)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listAccountsMissingHome = `-- name: ListAccountsMissingHome :many
SELECT
    id,
    username
FROM
    users
WHERE
    status = 'active'
    AND NOT EXISTS (
        SELECT
            1
        FROM
            path_access
        WHERE
            path_access.user_id = users.id
            AND path_access.device_serial = ''
            AND path_access.rel_path = 'users/' || users.username
            AND path_access.level = 'owner'
    )
ORDER BY
    id
`

type ListAccountsMissingHomeRow struct {
	ID       int64
	Username string
}

// ListAccountsMissingHome names every active account that does not own its
// home, which the startup repair then gives one (#1908). The grant is what
// matters rather than the directory: a home with no row is unreachable to the
// account it was made for, so both cases have to come back from this one query.
// The path is spelled the way authutil.homeRelPath spells it, on the internal
// device, whose serial is ”.
func (q *Queries) ListAccountsMissingHome(ctx context.Context) ([]ListAccountsMissingHomeRow, error) {
	rows, err := q.db.QueryContext(ctx, listAccountsMissingHome)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAccountsMissingHomeRow
	for rows.Next() {
		var i ListAccountsMissingHomeRow
		if err := rows.Scan(&i.ID, &i.Username); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPathAccessForUser = `-- name: ListPathAccessForUser :many
SELECT
    device_serial,
    rel_path,
    level
FROM
    path_access
WHERE
    path_access.user_id = ?1
    OR path_access.group_id IN (
        SELECT
            group_id
        FROM
            group_members
        WHERE
            group_members.user_id = ?1
    )
    OR path_access.group_id IN (
        SELECT
            id
        FROM
            groups
        WHERE
            name = 'everyone'
            AND builtin = 1
    )
`

type ListPathAccessForUserRow struct {
	DeviceSerial string
	RelPath      string
	Level        string
}

// ListPathAccessForUser returns every row that applies to a user: their own,
// their groups', and the built-in everyone group's. accessutil resolves
// ancestors in memory from this one read.
func (q *Queries) ListPathAccessForUser(ctx context.Context, userID sql.NullInt64) ([]ListPathAccessForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listPathAccessForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPathAccessForUserRow
	for rows.Next() {
		var i ListPathAccessForUserRow
		if err := rows.Scan(&i.DeviceSerial, &i.RelPath, &i.Level); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const movePathAccessTree = `-- name: MovePathAccessTree :execrows
UPDATE path_access
SET
    device_serial = ?1,
    rel_path = ?2 || substr(rel_path, length(CAST(?3 AS TEXT)) + 1)
WHERE
    device_serial = ?4
    AND (
        rel_path = ?3
        OR substr(rel_path, 1, length(?3) + 1) = ?3 || '/'
    )
`

type MovePathAccessTreeParams struct {
	NewDeviceSerial string
	NewRelPath      string
	OldRelPath      string
	OldDeviceSerial string
}

// MovePathAccessTree points the rows on a path and everything beneath it at
// where it moved, onto another device as well. substr, not LIKE: LIKE is
// case-insensitive and treats _ and % as wildcards, and "foo" must not match
// "foobar". The CAST gives sqlc a type for the parameter inside length().
func (q *Queries) MovePathAccessTree(ctx context.Context, arg MovePathAccessTreeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, movePathAccessTree,
		arg.NewDeviceSerial,
		arg.NewRelPath,
		arg.OldRelPath,
		arg.OldDeviceSerial,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const reassignOwnerRows = `-- name: ReassignOwnerRows :execrows
INSERT INTO
    path_access (device_serial, rel_path, user_id, level)
SELECT
    device_serial,
    rel_path,
    CAST(?1 AS INTEGER),
    'owner'
FROM
    path_access
WHERE
    path_access.user_id = ?2
    AND level = 'owner' ON CONFLICT (user_id, device_serial, rel_path)
WHERE
    user_id IS NOT NULL DO
UPDATE
SET
    level = 'owner'
`

type ReassignOwnerRowsParams struct {
	ToUserID   int64
	FromUserID sql.NullInt64
}

// ReassignOwnerRows gives an heir every path one user owns, before that user
// is deleted and ON DELETE CASCADE drops the rest of their rows (#1909). A
// path the heir already has a row on becomes theirs to own. The WHERE clause
// is load-bearing: without one, SQLite reads the ON of the upsert as a join
// constraint of the SELECT. The CAST gives sqlc a type for the heir's id.
func (q *Queries) ReassignOwnerRows(ctx context.Context, arg ReassignOwnerRowsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, reassignOwnerRows, arg.ToUserID, arg.FromUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setUserPathAccess = `-- name: SetUserPathAccess :exec
INSERT INTO
    path_access (device_serial, rel_path, user_id, level)
VALUES
    (?, ?, ?, ?) ON CONFLICT (user_id, device_serial, rel_path)
WHERE
    user_id IS NOT NULL DO
UPDATE
SET
    level = excluded.level
`

type SetUserPathAccessParams struct {
	DeviceSerial string
	RelPath      string
	UserID       sql.NullInt64
	Level        string
}

// SetUserPathAccess grants a user a level on a path, replacing the level any
// earlier grant to that user on that path carried.
func (q *Queries) SetUserPathAccess(ctx context.Context, arg SetUserPathAccessParams) error {
	_, err := q.db.ExecContext(ctx, setUserPathAccess,
		arg.DeviceSerial,
		arg.RelPath,
		arg.UserID,
		arg.Level,
	)
	return err
}
