// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: access.sql

package db

import (
	"context"
	"database/sql"
)

const deleteGroupPathAccess = `-- name: DeleteGroupPathAccess :execrows
DELETE FROM path_access
WHERE
    group_id = ?
    AND device_serial = ?
    AND rel_path = ?
`

type DeleteGroupPathAccessParams struct {
	GroupID      sql.NullInt64
	DeviceSerial string
	RelPath      string
}

// DeleteGroupPathAccess drops a group's row on exactly one path.
func (q *Queries) DeleteGroupPathAccess(ctx context.Context, arg DeleteGroupPathAccessParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteGroupPathAccess, arg.GroupID, arg.DeviceSerial, arg.RelPath)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deletePathAccessTree = `-- name: DeletePathAccessTree :execrows
DELETE FROM path_access
WHERE
    device_serial = ?1
    AND (
        rel_path = ?2
        OR substr(rel_path, 1, length(?2) + 1) = ?2 || '/'
    )
`

type DeletePathAccessTreeParams struct {
	DeviceSerial string
	RelPath      string
}

// DeletePathAccessTree drops the rows on a path and everything beneath it.
func (q *Queries) DeletePathAccessTree(ctx context.Context, arg DeletePathAccessTreeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deletePathAccessTree, arg.DeviceSerial, arg.RelPath)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteUserPathAccess = `-- name: DeleteUserPathAccess :execrows
DELETE FROM path_access
WHERE
    user_id = ?
    AND device_serial = ?
    AND rel_path = ?
`

type DeleteUserPathAccessParams struct {
	UserID       sql.NullInt64
	DeviceSerial string
	RelPath      string
}

// DeleteUserPathAccess drops a user's row on exactly one path. Rows on the
// folders that hold it stay.
func (q *Queries) DeleteUserPathAccess(ctx context.Context, arg DeleteUserPathAccessParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteUserPathAccess, arg.UserID, arg.DeviceSerial, arg.RelPath)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listPathAccessForUser = `-- name: ListPathAccessForUser :many
SELECT
    device_serial,
    rel_path,
    level
FROM
    path_access
WHERE
    path_access.user_id = ?1
    OR path_access.group_id IN (
        SELECT
            group_id
        FROM
            group_members
        WHERE
            group_members.user_id = ?1
    )
    OR path_access.group_id IN (
        SELECT
            id
        FROM
            groups
        WHERE
            name = 'everyone'
            AND builtin = 1
    )
`

type ListPathAccessForUserRow struct {
	DeviceSerial string
	RelPath      string
	Level        string
}

// ListPathAccessForUser returns every row that applies to a user: their own,
// their groups', and the built-in everyone group's. accessutil resolves
// ancestors in memory from this one read.
func (q *Queries) ListPathAccessForUser(ctx context.Context, userID sql.NullInt64) ([]ListPathAccessForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listPathAccessForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPathAccessForUserRow
	for rows.Next() {
		var i ListPathAccessForUserRow
		if err := rows.Scan(&i.DeviceSerial, &i.RelPath, &i.Level); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPathAccessOnAncestors = `-- name: ListPathAccessOnAncestors :many
SELECT
    path_access.rel_path,
    path_access.level,
    path_access.user_id,
    path_access.group_id,
    CAST(COALESCE(users.username, groups.name) AS TEXT) AS name,
    CAST(COALESCE(groups.builtin, 0) AS INTEGER) AS builtin
FROM
    path_access
    LEFT JOIN users ON users.id = path_access.user_id
    LEFT JOIN groups ON groups.id = path_access.group_id
WHERE
    path_access.device_serial = ?1
    AND (
        path_access.rel_path = ''
        OR path_access.rel_path = ?2
        OR substr(?2, 1, length(path_access.rel_path) + 1) = path_access.rel_path || '/'
    )
`

type ListPathAccessOnAncestorsParams struct {
	DeviceSerial string
	RelPath      string
}

type ListPathAccessOnAncestorsRow struct {
	RelPath string
	Level   string
	UserID  sql.NullInt64
	GroupID sql.NullInt64
	Name    string
	Builtin int64
}

// ListPathAccessOnAncestors lists the rows on a path and on every folder that
// holds it, with the name of the account or group each one was granted to,
// for the sharing sheet (#1911). substr, not LIKE, for the reason
// MovePathAccessTree gives. The CASTs give sqlc a type for each COALESCE.
func (q *Queries) ListPathAccessOnAncestors(ctx context.Context, arg ListPathAccessOnAncestorsParams) ([]ListPathAccessOnAncestorsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPathAccessOnAncestors, arg.DeviceSerial, arg.RelPath)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPathAccessOnAncestorsRow
	for rows.Next() {
		var i ListPathAccessOnAncestorsRow
		if err := rows.Scan(
			&i.RelPath,
			&i.Level,
			&i.UserID,
			&i.GroupID,
			&i.Name,
			&i.Builtin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const movePathAccessTree = `-- name: MovePathAccessTree :execrows
UPDATE path_access
SET
    device_serial = ?1,
    rel_path = ?2 || substr(rel_path, length(CAST(?3 AS TEXT)) + 1)
WHERE
    device_serial = ?4
    AND (
        rel_path = ?3
        OR substr(rel_path, 1, length(?3) + 1) = ?3 || '/'
    )
`

type MovePathAccessTreeParams struct {
	NewDeviceSerial string
	NewRelPath      string
	OldRelPath      string
	OldDeviceSerial string
}

// MovePathAccessTree points the rows on a path and everything beneath it at
// where it moved, onto another device as well. substr, not LIKE: LIKE is
// case-insensitive and treats _ and % as wildcards, and "foo" must not match
// "foobar". The CAST gives sqlc a type for the parameter inside length().
func (q *Queries) MovePathAccessTree(ctx context.Context, arg MovePathAccessTreeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, movePathAccessTree,
		arg.NewDeviceSerial,
		arg.NewRelPath,
		arg.OldRelPath,
		arg.OldDeviceSerial,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const reassignOwnerRows = `-- name: ReassignOwnerRows :execrows
INSERT INTO
    path_access (device_serial, rel_path, user_id, level)
SELECT
    device_serial,
    rel_path,
    CAST(?1 AS INTEGER),
    'owner'
FROM
    path_access
WHERE
    path_access.user_id = ?2
    AND level = 'owner' ON CONFLICT (user_id, device_serial, rel_path)
WHERE
    user_id IS NOT NULL DO
UPDATE
SET
    level = 'owner'
`

type ReassignOwnerRowsParams struct {
	ToUserID   int64
	FromUserID sql.NullInt64
}

// ReassignOwnerRows gives an heir every path one user owns, before that user
// is deleted and ON DELETE CASCADE drops the rest of their rows (#1909). A
// path the heir already has a row on becomes theirs to own. The WHERE clause
// is load-bearing: without one, SQLite reads the ON of the upsert as a join
// constraint of the SELECT. The CAST gives sqlc a type for the heir's id.
func (q *Queries) ReassignOwnerRows(ctx context.Context, arg ReassignOwnerRowsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, reassignOwnerRows, arg.ToUserID, arg.FromUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setGroupPathAccess = `-- name: SetGroupPathAccess :exec
INSERT INTO
    path_access (device_serial, rel_path, group_id, level)
VALUES
    (?, ?, ?, ?) ON CONFLICT (group_id, device_serial, rel_path)
WHERE
    group_id IS NOT NULL DO
UPDATE
SET
    level = excluded.level
`

type SetGroupPathAccessParams struct {
	DeviceSerial string
	RelPath      string
	GroupID      sql.NullInt64
	Level        string
}

// SetGroupPathAccess grants a group a level on a path, replacing the level any
// earlier grant to that group on that path carried.
func (q *Queries) SetGroupPathAccess(ctx context.Context, arg SetGroupPathAccessParams) error {
	_, err := q.db.ExecContext(ctx, setGroupPathAccess,
		arg.DeviceSerial,
		arg.RelPath,
		arg.GroupID,
		arg.Level,
	)
	return err
}

const setUserPathAccess = `-- name: SetUserPathAccess :exec
INSERT INTO
    path_access (device_serial, rel_path, user_id, level)
VALUES
    (?, ?, ?, ?) ON CONFLICT (user_id, device_serial, rel_path)
WHERE
    user_id IS NOT NULL DO
UPDATE
SET
    level = excluded.level
`

type SetUserPathAccessParams struct {
	DeviceSerial string
	RelPath      string
	UserID       sql.NullInt64
	Level        string
}

// SetUserPathAccess grants a user a level on a path, replacing the level any
// earlier grant to that user on that path carried.
func (q *Queries) SetUserPathAccess(ctx context.Context, arg SetUserPathAccessParams) error {
	_, err := q.db.ExecContext(ctx, setUserPathAccess,
		arg.DeviceSerial,
		arg.RelPath,
		arg.UserID,
		arg.Level,
	)
	return err
}
