// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin.sql

package db

import (
	"context"
	"time"
)

const countActiveAdmins = `-- name: CountActiveAdmins :one
SELECT COUNT(*) FROM users WHERE is_admin = 1 AND status = 'active'
`

// A disabled admin cannot sign in, so only active admins count (#1908).
func (q *Queries) CountActiveAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const demoteFromAdmin = `-- name: DemoteFromAdmin :one
UPDATE users SET is_admin = 0 WHERE username = ? RETURNING id, username, is_admin, created_at
`

type DemoteFromAdminRow struct {
	ID        int64
	Username  string
	IsAdmin   int64
	CreatedAt time.Time
}

func (q *Queries) DemoteFromAdmin(ctx context.Context, username string) (DemoteFromAdminRow, error) {
	row := q.db.QueryRowContext(ctx, demoteFromAdmin, username)
	var i DemoteFromAdminRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.IsAdmin,
		&i.CreatedAt,
	)
	return i, err
}

const isUserAdmin = `-- name: IsUserAdmin :one
SELECT is_admin FROM users WHERE username = ?
`

func (q *Queries) IsUserAdmin(ctx context.Context, username string) (int64, error) {
	row := q.db.QueryRowContext(ctx, isUserAdmin, username)
	var is_admin int64
	err := row.Scan(&is_admin)
	return is_admin, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, is_admin, status, created_at FROM users ORDER BY created_at ASC
`

type ListUsersRow struct {
	ID        int64
	Username  string
	IsAdmin   int64
	Status    string
	CreatedAt time.Time
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.IsAdmin,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const promoteToAdmin = `-- name: PromoteToAdmin :one
UPDATE users SET is_admin = 1 WHERE username = ? AND status = 'active' RETURNING id, username, is_admin, created_at
`

type PromoteToAdminRow struct {
	ID        int64
	Username  string
	IsAdmin   int64
	CreatedAt time.Time
}

// Only an active account can be promoted; anything else matches no row.
func (q *Queries) PromoteToAdmin(ctx context.Context, username string) (PromoteToAdminRow, error) {
	row := q.db.QueryRowContext(ctx, promoteToAdmin, username)
	var i PromoteToAdminRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.IsAdmin,
		&i.CreatedAt,
	)
	return i, err
}

const setUserAdmin = `-- name: SetUserAdmin :exec
UPDATE users SET is_admin = ? WHERE username = ?
`

type SetUserAdminParams struct {
	IsAdmin  int64
	Username string
}

func (q *Queries) SetUserAdmin(ctx context.Context, arg SetUserAdminParams) error {
	_, err := q.db.ExecContext(ctx, setUserAdmin, arg.IsAdmin, arg.Username)
	return err
}
