// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package db

import (
	"context"
	"time"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPendingUser = `-- name: CreatePendingUser :one
INSERT INTO users (username, password_hash, recovery_phrase_hash, auth_key_hash, auth_salt, status)
VALUES (?, ?, ?, ?, ?, 'pending')
RETURNING id, username, password_hash, recovery_phrase_hash, created_at, is_admin, status, auth_salt, auth_key_hash
`

type CreatePendingUserParams struct {
	Username           string
	PasswordHash       string
	RecoveryPhraseHash string
	AuthKeyHash        string
	AuthSalt           string
}

// CreatePendingUser records an account request from the sign-in page (#1908).
// It cannot sign in until an admin approves it.
func (q *Queries) CreatePendingUser(ctx context.Context, arg CreatePendingUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createPendingUser,
		arg.Username,
		arg.PasswordHash,
		arg.RecoveryPhraseHash,
		arg.AuthKeyHash,
		arg.AuthSalt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.RecoveryPhraseHash,
		&i.CreatedAt,
		&i.IsAdmin,
		&i.Status,
		&i.AuthSalt,
		&i.AuthKeyHash,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (token, user_id, expires_at, last_used_at)
VALUES (?, ?, ?, ?)
RETURNING token, user_id, expires_at, created_at, last_used_at
`

type CreateSessionParams struct {
	Token      string
	UserID     int64
	ExpiresAt  time.Time
	LastUsedAt time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.Token,
		arg.UserID,
		arg.ExpiresAt,
		arg.LastUsedAt,
	)
	var i Session
	err := row.Scan(
		&i.Token,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, password_hash, recovery_phrase_hash, auth_key_hash, auth_salt)
VALUES (?, ?, ?, ?, ?)
RETURNING id, username, password_hash, recovery_phrase_hash, created_at, is_admin, status, auth_salt, auth_key_hash
`

type CreateUserParams struct {
	Username           string
	PasswordHash       string
	RecoveryPhraseHash string
	AuthKeyHash        string
	AuthSalt           string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Username,
		arg.PasswordHash,
		arg.RecoveryPhraseHash,
		arg.AuthKeyHash,
		arg.AuthSalt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.RecoveryPhraseHash,
		&i.CreatedAt,
		&i.IsAdmin,
		&i.Status,
		&i.AuthSalt,
		&i.AuthKeyHash,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at <= datetime('now')
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions)
	return err
}

const deleteOtherUserSessions = `-- name: DeleteOtherUserSessions :exec
DELETE FROM sessions WHERE user_id = ? AND token != ?
`

type DeleteOtherUserSessionsParams struct {
	UserID int64
	Token  string
}

// "Sign out everywhere else" (#1663): every session of the user but the one
// the request came in on.
func (q *Queries) DeleteOtherUserSessions(ctx context.Context, arg DeleteOtherUserSessionsParams) error {
	_, err := q.db.ExecContext(ctx, deleteOtherUserSessions, arg.UserID, arg.Token)
	return err
}

const deletePendingUser = `-- name: DeletePendingUser :execrows
DELETE FROM users WHERE username = ? AND status = 'pending'
`

// DeletePendingUser denies an account request. Only a pending row matches, so
// a request that was already approved is left alone.
func (q *Queries) DeletePendingUser(ctx context.Context, username string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deletePendingUser, username)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token = ?
`

func (q *Queries) DeleteSession(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, token)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = ?
`

// Deletes one user. sessions.user_id is ON DELETE CASCADE (001_auth) and
// connections set _foreign_keys=on, so the user's sessions go with the row.
func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const deleteUserSessions = `-- name: DeleteUserSessions :exec
DELETE FROM sessions WHERE user_id = ?
`

func (q *Queries) DeleteUserSessions(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteUserSessions, userID)
	return err
}

const getSession = `-- name: GetSession :one
SELECT s.token, s.user_id, s.expires_at, s.created_at, s.last_used_at, u.username
FROM sessions s
JOIN users u ON s.user_id = u.id
WHERE s.token = ? AND s.expires_at > datetime('now') AND u.status = 'active'
LIMIT 1
`

type GetSessionRow struct {
	Token      string
	UserID     int64
	ExpiresAt  time.Time
	CreatedAt  time.Time
	LastUsedAt time.Time
	Username   string
}

// Only an active account's session counts (#1908): a pending account has
// never been approved, and a disabled one was turned off.
func (q *Queries) GetSession(ctx context.Context, token string) (GetSessionRow, error) {
	row := q.db.QueryRowContext(ctx, getSession, token)
	var i GetSessionRow
	err := row.Scan(
		&i.Token,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.Username,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, password_hash, recovery_phrase_hash, created_at, is_admin, status, auth_salt, auth_key_hash FROM users WHERE id = ? LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.RecoveryPhraseHash,
		&i.CreatedAt,
		&i.IsAdmin,
		&i.Status,
		&i.AuthSalt,
		&i.AuthKeyHash,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password_hash, recovery_phrase_hash, created_at, is_admin, status, auth_salt, auth_key_hash FROM users WHERE username = ? LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.RecoveryPhraseHash,
		&i.CreatedAt,
		&i.IsAdmin,
		&i.Status,
		&i.AuthSalt,
		&i.AuthKeyHash,
	)
	return i, err
}

const listActiveSessionsForUser = `-- name: ListActiveSessionsForUser :many
SELECT token, user_id, expires_at, created_at, last_used_at
FROM sessions
WHERE user_id = ? AND expires_at > datetime('now')
ORDER BY created_at DESC
`

func (q *Queries) ListActiveSessionsForUser(ctx context.Context, userID int64) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listActiveSessionsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.Token,
			&i.UserID,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveUsers = `-- name: ListActiveUsers :many
SELECT id, username FROM users WHERE status = 'active' ORDER BY username
`

type ListActiveUsersRow struct {
	ID       int64
	Username string
}

// ListActiveUsers lists the accounts a file or folder can be shared with
// (#1911): active ones only, and nothing about them beyond their names.
func (q *Queries) ListActiveUsers(ctx context.Context) ([]ListActiveUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveUsersRow
	for rows.Next() {
		var i ListActiveUsersRow
		if err := rows.Scan(&i.ID, &i.Username); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renewSession = `-- name: RenewSession :exec
UPDATE sessions
SET expires_at = ?, last_used_at = ?
WHERE token = ?
`

type RenewSessionParams struct {
	ExpiresAt  time.Time
	LastUsedAt time.Time
	Token      string
}

// Slides a session's expiry forward on use (#1647). The new expiry is computed
// in Go so the cap against created_at stays testable; this only writes it.
func (q *Queries) RenewSession(ctx context.Context, arg RenewSessionParams) error {
	_, err := q.db.ExecContext(ctx, renewSession, arg.ExpiresAt, arg.LastUsedAt, arg.Token)
	return err
}

const setAuthKeyIfUnset = `-- name: SetAuthKeyIfUnset :exec
UPDATE users
SET auth_key_hash = ?, auth_salt = ?
WHERE id = ? AND auth_key_hash = ''
`

type SetAuthKeyIfUnsetParams struct {
	AuthKeyHash string
	AuthSalt    string
	ID          int64
}

// SetAuthKeyIfUnset upgrades an account to an auth key on a sign-in that
// carried both the password and the key (#2430). Only an empty hash matches,
// so an upgraded account's key is never overwritten.
func (q *Queries) SetAuthKeyIfUnset(ctx context.Context, arg SetAuthKeyIfUnsetParams) error {
	_, err := q.db.ExecContext(ctx, setAuthKeyIfUnset, arg.AuthKeyHash, arg.AuthSalt, arg.ID)
	return err
}

const setRecoveryPhraseIfUnset = `-- name: SetRecoveryPhraseIfUnset :execrows
UPDATE users
SET recovery_phrase_hash = ?
WHERE id = ? AND recovery_phrase_hash = ''
`

type SetRecoveryPhraseIfUnsetParams struct {
	RecoveryPhraseHash string
	ID                 int64
}

// SetRecoveryPhraseIfUnset gives an admin-created account its recovery phrase
// on its first sign-in (#1873). Only an empty hash matches, so two sign-ins at
// once cannot both hand out a phrase.
func (q *Queries) SetRecoveryPhraseIfUnset(ctx context.Context, arg SetRecoveryPhraseIfUnsetParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setRecoveryPhraseIfUnset, arg.RecoveryPhraseHash, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setUserCredentials = `-- name: SetUserCredentials :exec
UPDATE users
SET password_hash = ?, auth_key_hash = ?, auth_salt = ?
WHERE id = ?
`

type SetUserCredentialsParams struct {
	PasswordHash string
	AuthKeyHash  string
	AuthSalt     string
	ID           int64
}

// SetUserCredentials replaces everything an account signs in with (#2430). A
// recovery writes all three so that whichever of the password and the auth
// key it did not set is cleared, and the old one stops signing in.
func (q *Queries) SetUserCredentials(ctx context.Context, arg SetUserCredentialsParams) error {
	_, err := q.db.ExecContext(ctx, setUserCredentials,
		arg.PasswordHash,
		arg.AuthKeyHash,
		arg.AuthSalt,
		arg.ID,
	)
	return err
}

const setUserStatus = `-- name: SetUserStatus :execrows
UPDATE users
SET status = ?1
WHERE username = ?2 AND status = ?3
`

type SetUserStatusParams struct {
	ToStatus   string
	Username   string
	FromStatus string
}

// SetUserStatus moves an account from one status to another in one
// conditional update, so two admins acting at once cannot both succeed.
func (q *Queries) SetUserStatus(ctx context.Context, arg SetUserStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setUserStatus, arg.ToStatus, arg.Username, arg.FromStatus)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
