// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: calendar.sql

package db

import (
	"context"
	"database/sql"
)

const createCalendarEvent = `-- name: CreateCalendarEvent :one
INSERT INTO
    calendar_events (
        calendar_id,
        title,
        notes,
        location,
        starts_at,
        ends_at,
        all_day,
        time_zone,
        repeat,
        reminder_minutes,
        color_index,
        created_by
    )
VALUES
    (
        ?1,
        ?2,
        ?3,
        ?4,
        ?5,
        ?6,
        ?7,
        ?8,
        ?9,
        ?10,
        ?11,
        ?12
    )
RETURNING id, calendar_id, title, notes, location, starts_at, ends_at, all_day, time_zone, repeat, reminder_minutes, color_index, created_at, updated_at, created_by
`

type CreateCalendarEventParams struct {
	CalendarID      int64
	Title           string
	Notes           string
	Location        string
	StartsAt        string
	EndsAt          string
	AllDay          int64
	TimeZone        string
	Repeat          string
	ReminderMinutes sql.NullInt64
	ColorIndex      int64
	CreatedBy       sql.NullInt64
}

func (q *Queries) CreateCalendarEvent(ctx context.Context, arg CreateCalendarEventParams) (CalendarEvent, error) {
	row := q.db.QueryRowContext(ctx, createCalendarEvent,
		arg.CalendarID,
		arg.Title,
		arg.Notes,
		arg.Location,
		arg.StartsAt,
		arg.EndsAt,
		arg.AllDay,
		arg.TimeZone,
		arg.Repeat,
		arg.ReminderMinutes,
		arg.ColorIndex,
		arg.CreatedBy,
	)
	var i CalendarEvent
	err := row.Scan(
		&i.ID,
		&i.CalendarID,
		&i.Title,
		&i.Notes,
		&i.Location,
		&i.StartsAt,
		&i.EndsAt,
		&i.AllDay,
		&i.TimeZone,
		&i.Repeat,
		&i.ReminderMinutes,
		&i.ColorIndex,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const deleteCalendarEvent = `-- name: DeleteCalendarEvent :execrows
DELETE FROM calendar_events
WHERE
    id = ?1
`

func (q *Queries) DeleteCalendarEvent(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteCalendarEvent, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getCalendarEvent = `-- name: GetCalendarEvent :one
SELECT
    calendar_events.id, calendar_events.calendar_id, calendar_events.title, calendar_events.notes, calendar_events.location, calendar_events.starts_at, calendar_events.ends_at, calendar_events.all_day, calendar_events.time_zone, calendar_events.repeat, calendar_events.reminder_minutes, calendar_events.color_index, calendar_events.created_at, calendar_events.updated_at, calendar_events.created_by,
    CAST(COALESCE(users.username, '') AS TEXT) AS owner_name
FROM
    calendar_events
    LEFT JOIN users ON users.id = calendar_events.created_by
WHERE
    calendar_events.id = ?1
LIMIT
    1
`

type GetCalendarEventRow struct {
	CalendarEvent CalendarEvent
	OwnerName     string
}

// Reads carry the owner's username, empty for an event with no owner (#2544).
func (q *Queries) GetCalendarEvent(ctx context.Context, id int64) (GetCalendarEventRow, error) {
	row := q.db.QueryRowContext(ctx, getCalendarEvent, id)
	var i GetCalendarEventRow
	err := row.Scan(
		&i.CalendarEvent.ID,
		&i.CalendarEvent.CalendarID,
		&i.CalendarEvent.Title,
		&i.CalendarEvent.Notes,
		&i.CalendarEvent.Location,
		&i.CalendarEvent.StartsAt,
		&i.CalendarEvent.EndsAt,
		&i.CalendarEvent.AllDay,
		&i.CalendarEvent.TimeZone,
		&i.CalendarEvent.Repeat,
		&i.CalendarEvent.ReminderMinutes,
		&i.CalendarEvent.ColorIndex,
		&i.CalendarEvent.CreatedAt,
		&i.CalendarEvent.UpdatedAt,
		&i.CalendarEvent.CreatedBy,
		&i.OwnerName,
	)
	return i, err
}

const getDefaultCalendar = `-- name: GetDefaultCalendar :one
SELECT
    id, name, is_default, created_at
FROM
    calendars
WHERE
    is_default = 1
LIMIT
    1
`

func (q *Queries) GetDefaultCalendar(ctx context.Context) (Calendar, error) {
	row := q.db.QueryRowContext(ctx, getDefaultCalendar)
	var i Calendar
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const listCalendarEventsInRange = `-- name: ListCalendarEventsInRange :many
SELECT
    calendar_events.id, calendar_events.calendar_id, calendar_events.title, calendar_events.notes, calendar_events.location, calendar_events.starts_at, calendar_events.ends_at, calendar_events.all_day, calendar_events.time_zone, calendar_events.repeat, calendar_events.reminder_minutes, calendar_events.color_index, calendar_events.created_at, calendar_events.updated_at, calendar_events.created_by,
    CAST(COALESCE(users.username, '') AS TEXT) AS owner_name
FROM
    calendar_events
    LEFT JOIN users ON users.id = calendar_events.created_by
WHERE
    calendar_events.calendar_id = ?1
    AND calendar_events.starts_at < ?2
    AND (
        calendar_events.repeat != 'none'
        OR calendar_events.ends_at > ?3
    )
ORDER BY
    calendar_events.starts_at,
    calendar_events.id
`

type ListCalendarEventsInRangeParams struct {
	CalendarID int64
	RangeEnd   string
	RangeStart string
}

type ListCalendarEventsInRangeRow struct {
	CalendarEvent CalendarEvent
	OwnerName     string
}

// A one-off event is listed when it overlaps [range_start, range_end). A
// repeating event is listed when its series starts before range_end, since any
// of its occurrences may fall in the range; the app expands them.
func (q *Queries) ListCalendarEventsInRange(ctx context.Context, arg ListCalendarEventsInRangeParams) ([]ListCalendarEventsInRangeRow, error) {
	rows, err := q.db.QueryContext(ctx, listCalendarEventsInRange, arg.CalendarID, arg.RangeEnd, arg.RangeStart)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCalendarEventsInRangeRow
	for rows.Next() {
		var i ListCalendarEventsInRangeRow
		if err := rows.Scan(
			&i.CalendarEvent.ID,
			&i.CalendarEvent.CalendarID,
			&i.CalendarEvent.Title,
			&i.CalendarEvent.Notes,
			&i.CalendarEvent.Location,
			&i.CalendarEvent.StartsAt,
			&i.CalendarEvent.EndsAt,
			&i.CalendarEvent.AllDay,
			&i.CalendarEvent.TimeZone,
			&i.CalendarEvent.Repeat,
			&i.CalendarEvent.ReminderMinutes,
			&i.CalendarEvent.ColorIndex,
			&i.CalendarEvent.CreatedAt,
			&i.CalendarEvent.UpdatedAt,
			&i.CalendarEvent.CreatedBy,
			&i.OwnerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCalendarEvent = `-- name: UpdateCalendarEvent :one
UPDATE calendar_events
SET
    title = ?1,
    notes = ?2,
    location = ?3,
    starts_at = ?4,
    ends_at = ?5,
    all_day = ?6,
    time_zone = ?7,
    repeat = ?8,
    reminder_minutes = ?9,
    color_index = ?10,
    updated_at = datetime('now')
WHERE
    id = ?11
RETURNING id, calendar_id, title, notes, location, starts_at, ends_at, all_day, time_zone, repeat, reminder_minutes, color_index, created_at, updated_at, created_by
`

type UpdateCalendarEventParams struct {
	Title           string
	Notes           string
	Location        string
	StartsAt        string
	EndsAt          string
	AllDay          int64
	TimeZone        string
	Repeat          string
	ReminderMinutes sql.NullInt64
	ColorIndex      int64
	ID              int64
}

func (q *Queries) UpdateCalendarEvent(ctx context.Context, arg UpdateCalendarEventParams) (CalendarEvent, error) {
	row := q.db.QueryRowContext(ctx, updateCalendarEvent,
		arg.Title,
		arg.Notes,
		arg.Location,
		arg.StartsAt,
		arg.EndsAt,
		arg.AllDay,
		arg.TimeZone,
		arg.Repeat,
		arg.ReminderMinutes,
		arg.ColorIndex,
		arg.ID,
	)
	var i CalendarEvent
	err := row.Scan(
		&i.ID,
		&i.CalendarID,
		&i.Title,
		&i.Notes,
		&i.Location,
		&i.StartsAt,
		&i.EndsAt,
		&i.AllDay,
		&i.TimeZone,
		&i.Repeat,
		&i.ReminderMinutes,
		&i.ColorIndex,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
	)
	return i, err
}
