// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chat_channel_keys.sql

package db

import (
	"context"
	"database/sql"
)

const createChatChannelEvent = `-- name: CreateChatChannelEvent :one
INSERT INTO chat_channel_events (channel_id, kind, actor_id, payload) VALUES (?, ?, ?, ?) RETURNING id, channel_id, kind, actor_id, payload, signature, signer_sign_key, created_at
`

type CreateChatChannelEventParams struct {
	ChannelID int64
	Kind      string
	ActorID   sql.NullInt64
	Payload   string
}

func (q *Queries) CreateChatChannelEvent(ctx context.Context, arg CreateChatChannelEventParams) (ChatChannelEvent, error) {
	row := q.db.QueryRowContext(ctx, createChatChannelEvent,
		arg.ChannelID,
		arg.Kind,
		arg.ActorID,
		arg.Payload,
	)
	var i ChatChannelEvent
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.Kind,
		&i.ActorID,
		&i.Payload,
		&i.Signature,
		&i.SignerSignKey,
		&i.CreatedAt,
	)
	return i, err
}

const createChatChannelKey = `-- name: CreateChatChannelKey :one
INSERT INTO chat_channel_keys (channel_id, version, created_by) VALUES (?, ?, ?) RETURNING channel_id, version, created_by, created_at
`

type CreateChatChannelKeyParams struct {
	ChannelID int64
	Version   int64
	CreatedBy sql.NullInt64
}

func (q *Queries) CreateChatChannelKey(ctx context.Context, arg CreateChatChannelKeyParams) (ChatChannelKey, error) {
	row := q.db.QueryRowContext(ctx, createChatChannelKey, arg.ChannelID, arg.Version, arg.CreatedBy)
	var i ChatChannelKey
	err := row.Scan(
		&i.ChannelID,
		&i.Version,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUserChatKeyGrants = `-- name: DeleteUserChatKeyGrants :exec
DELETE FROM chat_key_grants WHERE user_id = ?
`

// DeleteUserChatKeyGrants drops every grant sealed to an account, for when its
// X25519 key changes and they can no longer be opened.
func (q *Queries) DeleteUserChatKeyGrants(ctx context.Context, userID sql.NullInt64) error {
	_, err := q.db.ExecContext(ctx, deleteUserChatKeyGrants, userID)
	return err
}

const getChatChannelEvent = `-- name: GetChatChannelEvent :one
SELECT id, channel_id, kind, actor_id, payload, signature, signer_sign_key, created_at FROM chat_channel_events WHERE id = ? AND channel_id = ?
`

type GetChatChannelEventParams struct {
	ID        int64
	ChannelID int64
}

func (q *Queries) GetChatChannelEvent(ctx context.Context, arg GetChatChannelEventParams) (ChatChannelEvent, error) {
	row := q.db.QueryRowContext(ctx, getChatChannelEvent, arg.ID, arg.ChannelID)
	var i ChatChannelEvent
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.Kind,
		&i.ActorID,
		&i.Payload,
		&i.Signature,
		&i.SignerSignKey,
		&i.CreatedAt,
	)
	return i, err
}

const getChatKeyGrant = `-- name: GetChatKeyGrant :one
SELECT id, channel_id, version, user_id, sealed_key, granted_by, granter_sign_key, signature, created_at FROM chat_key_grants WHERE channel_id = ? AND version = ? AND user_id = ?
`

type GetChatKeyGrantParams struct {
	ChannelID int64
	Version   int64
	UserID    sql.NullInt64
}

func (q *Queries) GetChatKeyGrant(ctx context.Context, arg GetChatKeyGrantParams) (ChatKeyGrant, error) {
	row := q.db.QueryRowContext(ctx, getChatKeyGrant, arg.ChannelID, arg.Version, arg.UserID)
	var i ChatKeyGrant
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.Version,
		&i.UserID,
		&i.SealedKey,
		&i.GrantedBy,
		&i.GranterSignKey,
		&i.Signature,
		&i.CreatedAt,
	)
	return i, err
}

const insertChatKeyGrant = `-- name: InsertChatKeyGrant :exec
INSERT INTO chat_key_grants (
    channel_id, version, user_id, sealed_key, granted_by, granter_sign_key, signature
) VALUES (
    ?, ?, ?, ?, ?, ?, ?
) ON CONFLICT (channel_id, version, user_id) DO NOTHING
`

type InsertChatKeyGrantParams struct {
	ChannelID      int64
	Version        int64
	UserID         sql.NullInt64
	SealedKey      []byte
	GrantedBy      sql.NullInt64
	GranterSignKey []byte
	Signature      []byte
}

// InsertChatKeyGrant stores a grant unless the account already has one for
// that version: the first grant wins.
func (q *Queries) InsertChatKeyGrant(ctx context.Context, arg InsertChatKeyGrantParams) error {
	_, err := q.db.ExecContext(ctx, insertChatKeyGrant,
		arg.ChannelID,
		arg.Version,
		arg.UserID,
		arg.SealedKey,
		arg.GrantedBy,
		arg.GranterSignKey,
		arg.Signature,
	)
	return err
}

const listActiveUserChatPublicKeys = `-- name: ListActiveUserChatPublicKeys :many
SELECT
    user_chat_keys.user_id,
    user_chat_keys.box_public_key,
    user_chat_keys.sign_public_key
FROM
    user_chat_keys
    JOIN users ON users.id = user_chat_keys.user_id
WHERE
    users.status = 'active'
`

type ListActiveUserChatPublicKeysRow struct {
	UserID        int64
	BoxPublicKey  []byte
	SignPublicKey []byte
}

// ListActiveUserChatPublicKeys is every active account's published keys.
func (q *Queries) ListActiveUserChatPublicKeys(ctx context.Context) ([]ListActiveUserChatPublicKeysRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveUserChatPublicKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveUserChatPublicKeysRow
	for rows.Next() {
		var i ListActiveUserChatPublicKeysRow
		if err := rows.Scan(&i.UserID, &i.BoxPublicKey, &i.SignPublicKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChatChannelEvents = `-- name: ListChatChannelEvents :many
SELECT id, channel_id, kind, actor_id, payload, signature, signer_sign_key, created_at FROM chat_channel_events WHERE channel_id = ? AND id > ? ORDER BY id LIMIT ?
`

type ListChatChannelEventsParams struct {
	ChannelID int64
	ID        int64
	Limit     int64
}

// ListChatChannelEvents pages a channel's events oldest first, after an id.
func (q *Queries) ListChatChannelEvents(ctx context.Context, arg ListChatChannelEventsParams) ([]ChatChannelEvent, error) {
	rows, err := q.db.QueryContext(ctx, listChatChannelEvents, arg.ChannelID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatChannelEvent
	for rows.Next() {
		var i ChatChannelEvent
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.Kind,
			&i.ActorID,
			&i.Payload,
			&i.Signature,
			&i.SignerSignKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChatChannelIDs = `-- name: ListChatChannelIDs :many

SELECT id FROM chat_channels ORDER BY id
`

// Channel keys, key grants and channel events (#2417). The Quark stores sealed
// keys and signatures it can't open or make; clients do the crypto.
func (q *Queries) ListChatChannelIDs(ctx context.Context) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listChatChannelIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChatChannelKeys = `-- name: ListChatChannelKeys :many
SELECT channel_id, version, created_by, created_at FROM chat_channel_keys WHERE channel_id = ? ORDER BY version
`

func (q *Queries) ListChatChannelKeys(ctx context.Context, channelID int64) ([]ChatChannelKey, error) {
	rows, err := q.db.QueryContext(ctx, listChatChannelKeys, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatChannelKey
	for rows.Next() {
		var i ChatChannelKey
		if err := rows.Scan(
			&i.ChannelID,
			&i.Version,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChatKeyGrantRecipients = `-- name: ListChatKeyGrantRecipients :many
SELECT version, user_id FROM chat_key_grants WHERE channel_id = ? ORDER BY version, user_id
`

type ListChatKeyGrantRecipientsRow struct {
	Version int64
	UserID  sql.NullInt64
}

// ListChatKeyGrantRecipients is who holds which version of a channel's key. A
// NULL user_id is a grant to an account since deleted.
func (q *Queries) ListChatKeyGrantRecipients(ctx context.Context, channelID int64) ([]ListChatKeyGrantRecipientsRow, error) {
	rows, err := q.db.QueryContext(ctx, listChatKeyGrantRecipients, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChatKeyGrantRecipientsRow
	for rows.Next() {
		var i ListChatKeyGrantRecipientsRow
		if err := rows.Scan(&i.Version, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChatKeyGrantsForUser = `-- name: ListChatKeyGrantsForUser :many
SELECT id, channel_id, version, user_id, sealed_key, granted_by, granter_sign_key, signature, created_at FROM chat_key_grants WHERE channel_id = ? AND user_id = ? ORDER BY version
`

type ListChatKeyGrantsForUserParams struct {
	ChannelID int64
	UserID    sql.NullInt64
}

// ListChatKeyGrantsForUser is one account's grants on a channel, every version.
func (q *Queries) ListChatKeyGrantsForUser(ctx context.Context, arg ListChatKeyGrantsForUserParams) ([]ChatKeyGrant, error) {
	rows, err := q.db.QueryContext(ctx, listChatKeyGrantsForUser, arg.ChannelID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatKeyGrant
	for rows.Next() {
		var i ChatKeyGrant
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.Version,
			&i.UserID,
			&i.SealedKey,
			&i.GrantedBy,
			&i.GranterSignKey,
			&i.Signature,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const signChatChannelEvent = `-- name: SignChatChannelEvent :execrows
UPDATE chat_channel_events
SET
    signature = ?,
    signer_sign_key = ?
WHERE
    id = ?
    AND channel_id = ?
    AND actor_id = ?
    AND signature IS NULL
`

type SignChatChannelEventParams struct {
	Signature     []byte
	SignerSignKey []byte
	ID            int64
	ChannelID     int64
	ActorID       sql.NullInt64
}

// SignChatChannelEvent attaches the actor's signature to an event, once.
func (q *Queries) SignChatChannelEvent(ctx context.Context, arg SignChatChannelEventParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, signChatChannelEvent,
		arg.Signature,
		arg.SignerSignKey,
		arg.ID,
		arg.ChannelID,
		arg.ActorID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
