// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chat.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createChatChannel = `-- name: CreateChatChannel :one
INSERT INTO
    chat_channels (server_id, name, topic, created_by)
VALUES
    ((SELECT MIN(id) FROM chat_servers), ?, ?, ?) RETURNING id, server_id, kind, name, topic, is_default, created_by, created_at
`

type CreateChatChannelParams struct {
	Name      string
	Topic     string
	CreatedBy sql.NullInt64
}

// CreateChatChannel adds a channel to the Quark's one server.
func (q *Queries) CreateChatChannel(ctx context.Context, arg CreateChatChannelParams) (ChatChannel, error) {
	row := q.db.QueryRowContext(ctx, createChatChannel, arg.Name, arg.Topic, arg.CreatedBy)
	var i ChatChannel
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.Kind,
		&i.Name,
		&i.Topic,
		&i.IsDefault,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteChatChannel = `-- name: DeleteChatChannel :execrows
DELETE FROM chat_channels WHERE id = ? AND is_default = 0
`

// DeleteChatChannel drops a channel and, by ON DELETE CASCADE, its members.
// The default channel is never deleted.
func (q *Queries) DeleteChatChannel(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteChatChannel, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteChatChannelGroupMember = `-- name: DeleteChatChannelGroupMember :execrows
DELETE FROM chat_channel_members WHERE channel_id = ? AND group_id = ?
`

type DeleteChatChannelGroupMemberParams struct {
	ChannelID int64
	GroupID   sql.NullInt64
}

func (q *Queries) DeleteChatChannelGroupMember(ctx context.Context, arg DeleteChatChannelGroupMemberParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteChatChannelGroupMember, arg.ChannelID, arg.GroupID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteChatChannelUserMember = `-- name: DeleteChatChannelUserMember :execrows
DELETE FROM chat_channel_members WHERE channel_id = ? AND user_id = ?
`

type DeleteChatChannelUserMemberParams struct {
	ChannelID int64
	UserID    sql.NullInt64
}

func (q *Queries) DeleteChatChannelUserMember(ctx context.Context, arg DeleteChatChannelUserMemberParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteChatChannelUserMember, arg.ChannelID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getChatChannel = `-- name: GetChatChannel :one
SELECT id, server_id, kind, name, topic, is_default, created_by, created_at FROM chat_channels WHERE id = ? LIMIT 1
`

func (q *Queries) GetChatChannel(ctx context.Context, id int64) (ChatChannel, error) {
	row := q.db.QueryRowContext(ctx, getChatChannel, id)
	var i ChatChannel
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.Kind,
		&i.Name,
		&i.Topic,
		&i.IsDefault,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getChatChannelLevelForUser = `-- name: GetChatChannelLevelForUser :one
SELECT
    CAST(COALESCE(MAX(
        CASE chat_channel_members.level
            WHEN 'owner' THEN 3
            WHEN 'write' THEN 2
            ELSE 1
        END
    ), 0) AS INTEGER) AS level_rank
FROM
    chat_channel_members
WHERE
    chat_channel_members.channel_id = ?1
    AND (
        chat_channel_members.user_id = ?2
        OR chat_channel_members.group_id IN (
            SELECT
                group_id
            FROM
                group_members
            WHERE
                group_members.user_id = ?2
        )
        OR chat_channel_members.group_id IN (
            SELECT
                id
            FROM
                groups
            WHERE
                name = 'everyone'
                AND builtin = 1
        )
    )
`

type GetChatChannelLevelForUserParams struct {
	ChannelID int64
	UserID    sql.NullInt64
}

// GetChatChannelLevelForUser is an account's best level on one channel, 0
// when it is not a member.
func (q *Queries) GetChatChannelLevelForUser(ctx context.Context, arg GetChatChannelLevelForUserParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getChatChannelLevelForUser, arg.ChannelID, arg.UserID)
	var level_rank int64
	err := row.Scan(&level_rank)
	return level_rank, err
}

const listAllChatChannels = `-- name: ListAllChatChannels :many
SELECT
    chat_channels.id,
    chat_channels.server_id,
    chat_channels.kind,
    chat_channels.name,
    chat_channels.topic,
    chat_channels.is_default,
    chat_channels.created_by,
    chat_channels.created_at,
    CAST(NOT EXISTS (
        SELECT
            1
        FROM
            chat_channel_members AS everyone_rows
            JOIN groups ON groups.id = everyone_rows.group_id
        WHERE
            everyone_rows.channel_id = chat_channels.id
            AND groups.name = 'everyone'
            AND groups.builtin = 1
    ) AS INTEGER) AS is_private
FROM
    chat_channels
ORDER BY
    chat_channels.is_default DESC,
    chat_channels.name COLLATE NOCASE,
    chat_channels.id
`

type ListAllChatChannelsRow struct {
	ID        int64
	ServerID  int64
	Kind      string
	Name      string
	Topic     string
	IsDefault int64
	CreatedBy sql.NullInt64
	CreatedAt time.Time
	IsPrivate int64
}

// ListAllChatChannels is every channel on the Quark, for an admin looking
// for the ones they are not in (#2422), ordered as ListChatChannelsForUser.
func (q *Queries) ListAllChatChannels(ctx context.Context) ([]ListAllChatChannelsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllChatChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllChatChannelsRow
	for rows.Next() {
		var i ListAllChatChannelsRow
		if err := rows.Scan(
			&i.ID,
			&i.ServerID,
			&i.Kind,
			&i.Name,
			&i.Topic,
			&i.IsDefault,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.IsPrivate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChatChannelGroupUsers = `-- name: ListChatChannelGroupUsers :many
SELECT
    chat_channel_members.group_id,
    users.id AS user_id,
    users.username
FROM
    chat_channel_members
    JOIN groups ON groups.id = chat_channel_members.group_id
    JOIN users ON users.status = 'active'
    AND (
        (
            groups.name = 'everyone'
            AND groups.builtin = 1
        )
        OR users.id IN (
            SELECT
                user_id
            FROM
                group_members
            WHERE
                group_members.group_id = chat_channel_members.group_id
        )
    )
WHERE
    chat_channel_members.channel_id = ?
ORDER BY
    users.username COLLATE NOCASE
`

type ListChatChannelGroupUsersRow struct {
	GroupID  sql.NullInt64
	UserID   int64
	Username string
}

// ListChatChannelGroupUsers expands each group row on a channel into the
// active accounts in it; everyone holds every active account.
func (q *Queries) ListChatChannelGroupUsers(ctx context.Context, channelID int64) ([]ListChatChannelGroupUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listChatChannelGroupUsers, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChatChannelGroupUsersRow
	for rows.Next() {
		var i ListChatChannelGroupUsersRow
		if err := rows.Scan(&i.GroupID, &i.UserID, &i.Username); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChatChannelMemberUsers = `-- name: ListChatChannelMemberUsers :many
SELECT
    users.id,
    users.username,
    CAST(MAX(
        CASE chat_channel_members.level
            WHEN 'owner' THEN 3
            WHEN 'write' THEN 2
            ELSE 1
        END
    ) AS INTEGER) AS level_rank
FROM
    chat_channel_members
    LEFT JOIN groups ON groups.id = chat_channel_members.group_id
    JOIN users ON users.status = 'active'
    AND (
        users.id = chat_channel_members.user_id
        OR (
            groups.name = 'everyone'
            AND groups.builtin = 1
        )
        OR users.id IN (
            SELECT
                user_id
            FROM
                group_members
            WHERE
                group_members.group_id = chat_channel_members.group_id
        )
    )
WHERE
    chat_channel_members.channel_id = ?
GROUP BY
    users.id
ORDER BY
    users.username COLLATE NOCASE
`

type ListChatChannelMemberUsersRow struct {
	ID        int64
	Username  string
	LevelRank int64
}

// ListChatChannelMemberUsers resolves a channel's rows into the active
// accounts they reach, each with its best level.
func (q *Queries) ListChatChannelMemberUsers(ctx context.Context, channelID int64) ([]ListChatChannelMemberUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listChatChannelMemberUsers, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChatChannelMemberUsersRow
	for rows.Next() {
		var i ListChatChannelMemberUsersRow
		if err := rows.Scan(&i.ID, &i.Username, &i.LevelRank); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChatChannelMembers = `-- name: ListChatChannelMembers :many
SELECT
    chat_channel_members.user_id,
    chat_channel_members.group_id,
    chat_channel_members.level,
    CAST(COALESCE(users.username, groups.name) AS TEXT) AS name,
    CAST(COALESCE(groups.builtin, 0) AS INTEGER) AS builtin
FROM
    chat_channel_members
    LEFT JOIN users ON users.id = chat_channel_members.user_id
    LEFT JOIN groups ON groups.id = chat_channel_members.group_id
WHERE
    chat_channel_members.channel_id = ?
ORDER BY
    chat_channel_members.group_id IS NULL,
    name COLLATE NOCASE
`

type ListChatChannelMembersRow struct {
	UserID  sql.NullInt64
	GroupID sql.NullInt64
	Level   string
	Name    string
	Builtin int64
}

// ListChatChannelMembers lists a channel's rows with the name of the account
// or group each names. The CASTs give sqlc a type for each COALESCE.
func (q *Queries) ListChatChannelMembers(ctx context.Context, channelID int64) ([]ListChatChannelMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, listChatChannelMembers, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChatChannelMembersRow
	for rows.Next() {
		var i ListChatChannelMembersRow
		if err := rows.Scan(
			&i.UserID,
			&i.GroupID,
			&i.Level,
			&i.Name,
			&i.Builtin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChatChannelsForUser = `-- name: ListChatChannelsForUser :many
SELECT
    chat_channels.id,
    chat_channels.server_id,
    chat_channels.kind,
    chat_channels.name,
    chat_channels.topic,
    chat_channels.is_default,
    chat_channels.created_by,
    chat_channels.created_at,
    CAST(MAX(
        CASE chat_channel_members.level
            WHEN 'owner' THEN 3
            WHEN 'write' THEN 2
            ELSE 1
        END
    ) AS INTEGER) AS level_rank,
    CAST(NOT EXISTS (
        SELECT
            1
        FROM
            chat_channel_members AS everyone_rows
            JOIN groups ON groups.id = everyone_rows.group_id
        WHERE
            everyone_rows.channel_id = chat_channels.id
            AND groups.name = 'everyone'
            AND groups.builtin = 1
    ) AS INTEGER) AS is_private
FROM
    chat_channels
    JOIN chat_channel_members ON chat_channel_members.channel_id = chat_channels.id
WHERE
    chat_channel_members.user_id = ?1
    OR chat_channel_members.group_id IN (
        SELECT
            group_id
        FROM
            group_members
        WHERE
            group_members.user_id = ?1
    )
    OR chat_channel_members.group_id IN (
        SELECT
            id
        FROM
            groups
        WHERE
            name = 'everyone'
            AND builtin = 1
    )
GROUP BY
    chat_channels.id
ORDER BY
    chat_channels.is_default DESC,
    chat_channels.name COLLATE NOCASE,
    chat_channels.id
`

type ListChatChannelsForUserRow struct {
	ID        int64
	ServerID  int64
	Kind      string
	Name      string
	Topic     string
	IsDefault int64
	CreatedBy sql.NullInt64
	CreatedAt time.Time
	LevelRank int64
	IsPrivate int64
}

// ListChatChannelsForUser lists the channels an account is a member of,
// directly, through a group, or through everyone, with its best level on each.
// is_private is whether everyone has no row on the channel. Membership is
// additive and the best level wins, as ListPathAccessForUser resolves
// path_access; levels are ranked read = 1, write = 2, owner = 3 here and in
// the queries below so SQL can take the best one.
func (q *Queries) ListChatChannelsForUser(ctx context.Context, userID sql.NullInt64) ([]ListChatChannelsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listChatChannelsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChatChannelsForUserRow
	for rows.Next() {
		var i ListChatChannelsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.ServerID,
			&i.Kind,
			&i.Name,
			&i.Topic,
			&i.IsDefault,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.LevelRank,
			&i.IsPrivate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setChatChannelGroupMember = `-- name: SetChatChannelGroupMember :exec
INSERT INTO
    chat_channel_members (channel_id, group_id, level)
VALUES
    (?, ?, ?) ON CONFLICT (group_id, channel_id)
WHERE
    group_id IS NOT NULL DO
UPDATE
SET
    level = excluded.level
`

type SetChatChannelGroupMemberParams struct {
	ChannelID int64
	GroupID   sql.NullInt64
	Level     string
}

// SetChatChannelGroupMember gives a group a level on a channel, replacing the
// level any earlier row for it carried.
func (q *Queries) SetChatChannelGroupMember(ctx context.Context, arg SetChatChannelGroupMemberParams) error {
	_, err := q.db.ExecContext(ctx, setChatChannelGroupMember, arg.ChannelID, arg.GroupID, arg.Level)
	return err
}

const setChatChannelUserMember = `-- name: SetChatChannelUserMember :exec
INSERT INTO
    chat_channel_members (channel_id, user_id, level)
VALUES
    (?, ?, ?) ON CONFLICT (user_id, channel_id)
WHERE
    user_id IS NOT NULL DO
UPDATE
SET
    level = excluded.level
`

type SetChatChannelUserMemberParams struct {
	ChannelID int64
	UserID    sql.NullInt64
	Level     string
}

// SetChatChannelUserMember gives an account a level on a channel, replacing
// the level any earlier row for it carried.
func (q *Queries) SetChatChannelUserMember(ctx context.Context, arg SetChatChannelUserMemberParams) error {
	_, err := q.db.ExecContext(ctx, setChatChannelUserMember, arg.ChannelID, arg.UserID, arg.Level)
	return err
}

const updateChatChannel = `-- name: UpdateChatChannel :one
UPDATE chat_channels SET name = ?, topic = ? WHERE id = ? RETURNING id, server_id, kind, name, topic, is_default, created_by, created_at
`

type UpdateChatChannelParams struct {
	Name  string
	Topic string
	ID    int64
}

func (q *Queries) UpdateChatChannel(ctx context.Context, arg UpdateChatChannelParams) (ChatChannel, error) {
	row := q.db.QueryRowContext(ctx, updateChatChannel, arg.Name, arg.Topic, arg.ID)
	var i ChatChannel
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.Kind,
		&i.Name,
		&i.Topic,
		&i.IsDefault,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}
