// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chat_read_markers.sql

package db

import (
	"context"
)

const countChatUnreadForUser = `-- name: CountChatUnreadForUser :many
SELECT
    chat_messages.channel_id,
    COUNT(*) AS unread
FROM
    chat_messages
    LEFT JOIN chat_read_markers ON chat_read_markers.channel_id = chat_messages.channel_id
    AND chat_read_markers.user_id = ?1
WHERE
    chat_messages.id > COALESCE(chat_read_markers.last_read_message_id, 0)
    AND chat_messages.deleted_at IS NULL
    AND COALESCE(chat_messages.author_id, 0) <> ?1
GROUP BY
    chat_messages.channel_id
`

type CountChatUnreadForUserRow struct {
	ChannelID int64
	Unread    int64
}

// CountChatUnreadForUser counts, per channel, the messages after an account's
// marker that someone else wrote and that are not deleted. A channel with
// none has no row. It counts every channel, whatever the account may read
// there; chatutil keeps only the counts of channels it reads.
// ponytail: a channel never opened counts its whole history on every list.
// Cap the count or cache it if a long channel ever makes the list slow.
func (q *Queries) CountChatUnreadForUser(ctx context.Context, userID int64) ([]CountChatUnreadForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, countChatUnreadForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountChatUnreadForUserRow
	for rows.Next() {
		var i CountChatUnreadForUserRow
		if err := rows.Scan(&i.ChannelID, &i.Unread); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChatReadMarker = `-- name: GetChatReadMarker :one
SELECT last_read_message_id FROM chat_read_markers WHERE user_id = ? AND channel_id = ?
`

type GetChatReadMarkerParams struct {
	UserID    int64
	ChannelID int64
}

func (q *Queries) GetChatReadMarker(ctx context.Context, arg GetChatReadMarkerParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getChatReadMarker, arg.UserID, arg.ChannelID)
	var last_read_message_id int64
	err := row.Scan(&last_read_message_id)
	return last_read_message_id, err
}

const setChatReadMarker = `-- name: SetChatReadMarker :execrows

INSERT INTO chat_read_markers (user_id, channel_id, last_read_message_id)
VALUES (?, ?, ?)
ON CONFLICT (user_id, channel_id) DO UPDATE
SET last_read_message_id = excluded.last_read_message_id
WHERE excluded.last_read_message_id > chat_read_markers.last_read_message_id
`

type SetChatReadMarkerParams struct {
	UserID            int64
	ChannelID         int64
	LastReadMessageID int64
}

// Chat read markers (#2424): how far each account has read in each channel.
// SetChatReadMarker moves an account's marker in a channel forward, never
// backward: it changes no row when the marker is already at or past the id.
func (q *Queries) SetChatReadMarker(ctx context.Context, arg SetChatReadMarkerParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setChatReadMarker, arg.UserID, arg.ChannelID, arg.LastReadMessageID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
