// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chat_reactions.sql

package db

import (
	"context"
)

const countUserChatReactions = `-- name: CountUserChatReactions :one
SELECT COUNT(*) FROM chat_reactions WHERE message_id = ? AND user_id = ?
`

type CountUserChatReactionsParams struct {
	MessageID int64
	UserID    int64
}

// CountUserChatReactions is how many reactions one account has on a message.
func (q *Queries) CountUserChatReactions(ctx context.Context, arg CountUserChatReactionsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUserChatReactions, arg.MessageID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createChatReaction = `-- name: CreateChatReaction :one

INSERT INTO chat_reactions (message_id, user_id, key_version, ciphertext)
SELECT id, ?1, ?2, ?3
FROM chat_messages
WHERE chat_messages.id = ?4 AND deleted_at IS NULL
RETURNING id, message_id, user_id, key_version, ciphertext, created_at
`

type CreateChatReactionParams struct {
	UserID     int64
	KeyVersion int64
	Ciphertext []byte
	MessageID  int64
}

// Chat reactions (#2426). The Quark stores ciphertext and never opens it.
// CreateChatReaction stores a reaction on a message that isn't deleted, and
// returns no row when it is, so a reaction can't slip in after the tombstone.
func (q *Queries) CreateChatReaction(ctx context.Context, arg CreateChatReactionParams) (ChatReaction, error) {
	row := q.db.QueryRowContext(ctx, createChatReaction,
		arg.UserID,
		arg.KeyVersion,
		arg.Ciphertext,
		arg.MessageID,
	)
	var i ChatReaction
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.UserID,
		&i.KeyVersion,
		&i.Ciphertext,
		&i.CreatedAt,
	)
	return i, err
}

const deleteChatReaction = `-- name: DeleteChatReaction :exec
DELETE FROM chat_reactions WHERE id = ?
`

func (q *Queries) DeleteChatReaction(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteChatReaction, id)
	return err
}

const getChatReaction = `-- name: GetChatReaction :one
SELECT id, message_id, user_id, key_version, ciphertext, created_at FROM chat_reactions WHERE id = ?
`

func (q *Queries) GetChatReaction(ctx context.Context, id int64) (ChatReaction, error) {
	row := q.db.QueryRowContext(ctx, getChatReaction, id)
	var i ChatReaction
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.UserID,
		&i.KeyVersion,
		&i.Ciphertext,
		&i.CreatedAt,
	)
	return i, err
}

const listChatReactionsBetween = `-- name: ListChatReactionsBetween :many
SELECT chat_reactions.id, chat_reactions.message_id, chat_reactions.user_id, chat_reactions.key_version, chat_reactions.ciphertext, chat_reactions.created_at
FROM chat_reactions
JOIN chat_messages ON chat_messages.id = chat_reactions.message_id
WHERE chat_messages.channel_id = ?1
  AND chat_reactions.message_id >= ?2
  AND chat_reactions.message_id <= ?3
ORDER BY chat_reactions.id
`

type ListChatReactionsBetweenParams struct {
	ChannelID int64
	FirstID   int64
	LastID    int64
}

// ListChatReactionsBetween is the reactions on a channel's messages whose ids
// fall in [first_id, last_id], one page of ListChatMessages*.
func (q *Queries) ListChatReactionsBetween(ctx context.Context, arg ListChatReactionsBetweenParams) ([]ChatReaction, error) {
	rows, err := q.db.QueryContext(ctx, listChatReactionsBetween, arg.ChannelID, arg.FirstID, arg.LastID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatReaction
	for rows.Next() {
		var i ChatReaction
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.UserID,
			&i.KeyVersion,
			&i.Ciphertext,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
