// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chat_messages.sql

package db

import (
	"context"
	"database/sql"
)

const createChatMessage = `-- name: CreateChatMessage :one

INSERT INTO chat_messages (channel_id, author_id, key_version, ciphertext)
VALUES (?, ?, ?, ?)
RETURNING id, channel_id, author_id, key_version, ciphertext, created_at, edited_at, deleted_at
`

type CreateChatMessageParams struct {
	ChannelID  int64
	AuthorID   sql.NullInt64
	KeyVersion int64
	Ciphertext []byte
}

// Chat messages (#2418). The Quark stores ciphertext and never opens it.
func (q *Queries) CreateChatMessage(ctx context.Context, arg CreateChatMessageParams) (ChatMessage, error) {
	row := q.db.QueryRowContext(ctx, createChatMessage,
		arg.ChannelID,
		arg.AuthorID,
		arg.KeyVersion,
		arg.Ciphertext,
	)
	var i ChatMessage
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.AuthorID,
		&i.KeyVersion,
		&i.Ciphertext,
		&i.CreatedAt,
		&i.EditedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getChatMessage = `-- name: GetChatMessage :one
SELECT id, channel_id, author_id, key_version, ciphertext, created_at, edited_at, deleted_at FROM chat_messages WHERE id = ?
`

func (q *Queries) GetChatMessage(ctx context.Context, id int64) (ChatMessage, error) {
	row := q.db.QueryRowContext(ctx, getChatMessage, id)
	var i ChatMessage
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.AuthorID,
		&i.KeyVersion,
		&i.Ciphertext,
		&i.CreatedAt,
		&i.EditedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listChatMessagesAfter = `-- name: ListChatMessagesAfter :many
SELECT id, channel_id, author_id, key_version, ciphertext, created_at, edited_at, deleted_at FROM chat_messages WHERE channel_id = ? AND id > ? ORDER BY id LIMIT ?
`

type ListChatMessagesAfterParams struct {
	ChannelID int64
	ID        int64
	Limit     int64
}

// ListChatMessagesAfter pages a channel forward from an id, oldest first.
func (q *Queries) ListChatMessagesAfter(ctx context.Context, arg ListChatMessagesAfterParams) ([]ChatMessage, error) {
	rows, err := q.db.QueryContext(ctx, listChatMessagesAfter, arg.ChannelID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatMessage
	for rows.Next() {
		var i ChatMessage
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.AuthorID,
			&i.KeyVersion,
			&i.Ciphertext,
			&i.CreatedAt,
			&i.EditedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChatMessagesBefore = `-- name: ListChatMessagesBefore :many
SELECT id, channel_id, author_id, key_version, ciphertext, created_at, edited_at, deleted_at FROM chat_messages WHERE channel_id = ? AND id < ? ORDER BY id DESC LIMIT ?
`

type ListChatMessagesBeforeParams struct {
	ChannelID int64
	ID        int64
	Limit     int64
}

// ListChatMessagesBefore pages a channel backward from an id, newest first.
func (q *Queries) ListChatMessagesBefore(ctx context.Context, arg ListChatMessagesBeforeParams) ([]ChatMessage, error) {
	rows, err := q.db.QueryContext(ctx, listChatMessagesBefore, arg.ChannelID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatMessage
	for rows.Next() {
		var i ChatMessage
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.AuthorID,
			&i.KeyVersion,
			&i.Ciphertext,
			&i.CreatedAt,
			&i.EditedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tombstoneChatMessage = `-- name: TombstoneChatMessage :one
UPDATE chat_messages
SET ciphertext = NULL, deleted_at = COALESCE(deleted_at, datetime('now'))
WHERE id = ?
RETURNING id, channel_id, author_id, key_version, ciphertext, created_at, edited_at, deleted_at
`

// TombstoneChatMessage wipes a message's ciphertext and marks it deleted,
// keeping the first deletion time when it is deleted twice.
func (q *Queries) TombstoneChatMessage(ctx context.Context, id int64) (ChatMessage, error) {
	row := q.db.QueryRowContext(ctx, tombstoneChatMessage, id)
	var i ChatMessage
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.AuthorID,
		&i.KeyVersion,
		&i.Ciphertext,
		&i.CreatedAt,
		&i.EditedAt,
		&i.DeletedAt,
	)
	return i, err
}
