// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chat_keys.sql

package db

import (
	"context"
)

const deleteUserChatKeys = `-- name: DeleteUserChatKeys :exec
DELETE FROM user_chat_keys
WHERE
    user_id = ?
`

// DeleteUserChatKeys removes an account's chat identity. The foreign key
// cascades too, but deletion says so rather than relying on the pragma.
func (q *Queries) DeleteUserChatKeys(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteUserChatKeys, userID)
	return err
}

const getUserChatKeys = `-- name: GetUserChatKeys :one
SELECT
    user_id, box_public_key, sign_public_key, wrapped_by_password, salt_pw, wrapped_by_phrase, salt_rp, kdf_params, created_at, updated_at
FROM
    user_chat_keys
WHERE
    user_id = ?
`

// GetUserChatKeys returns an account's whole chat identity row, wrapped
// private seeds included. Only the account itself may be served it (#2416).
func (q *Queries) GetUserChatKeys(ctx context.Context, userID int64) (UserChatKey, error) {
	row := q.db.QueryRowContext(ctx, getUserChatKeys, userID)
	var i UserChatKey
	err := row.Scan(
		&i.UserID,
		&i.BoxPublicKey,
		&i.SignPublicKey,
		&i.WrappedByPassword,
		&i.SaltPw,
		&i.WrappedByPhrase,
		&i.SaltRp,
		&i.KdfParams,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserChatPublicKeys = `-- name: GetUserChatPublicKeys :one
SELECT
    user_chat_keys.user_id,
    user_chat_keys.box_public_key,
    user_chat_keys.sign_public_key
FROM
    user_chat_keys
    JOIN users ON users.id = user_chat_keys.user_id
WHERE
    user_chat_keys.user_id = ?
    AND users.status = 'active'
`

type GetUserChatPublicKeysRow struct {
	UserID        int64
	BoxPublicKey  []byte
	SignPublicKey []byte
}

// GetUserChatPublicKeys returns only the public half of an active account's
// chat identity, which any signed-in account may read.
func (q *Queries) GetUserChatPublicKeys(ctx context.Context, userID int64) (GetUserChatPublicKeysRow, error) {
	row := q.db.QueryRowContext(ctx, getUserChatPublicKeys, userID)
	var i GetUserChatPublicKeysRow
	err := row.Scan(&i.UserID, &i.BoxPublicKey, &i.SignPublicKey)
	return i, err
}

const upsertUserChatKeys = `-- name: UpsertUserChatKeys :one
INSERT INTO user_chat_keys (
    user_id,
    box_public_key,
    sign_public_key,
    wrapped_by_password,
    salt_pw,
    wrapped_by_phrase,
    salt_rp,
    kdf_params
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?
)
ON CONFLICT (user_id) DO UPDATE SET
    box_public_key = excluded.box_public_key,
    sign_public_key = excluded.sign_public_key,
    wrapped_by_password = excluded.wrapped_by_password,
    salt_pw = excluded.salt_pw,
    wrapped_by_phrase = excluded.wrapped_by_phrase,
    salt_rp = excluded.salt_rp,
    kdf_params = excluded.kdf_params,
    updated_at = datetime('now')
RETURNING
    user_id, box_public_key, sign_public_key, wrapped_by_password, salt_pw, wrapped_by_phrase, salt_rp, kdf_params, created_at, updated_at
`

type UpsertUserChatKeysParams struct {
	UserID            int64
	BoxPublicKey      []byte
	SignPublicKey     []byte
	WrappedByPassword []byte
	SaltPw            []byte
	WrappedByPhrase   []byte
	SaltRp            []byte
	KdfParams         string
}

// UpsertUserChatKeys creates or replaces an account's chat identity row.
// created_at survives a replace, so it dates the account's first key.
func (q *Queries) UpsertUserChatKeys(ctx context.Context, arg UpsertUserChatKeysParams) (UserChatKey, error) {
	row := q.db.QueryRowContext(ctx, upsertUserChatKeys,
		arg.UserID,
		arg.BoxPublicKey,
		arg.SignPublicKey,
		arg.WrappedByPassword,
		arg.SaltPw,
		arg.WrappedByPhrase,
		arg.SaltRp,
		arg.KdfParams,
	)
	var i UserChatKey
	err := row.Scan(
		&i.UserID,
		&i.BoxPublicKey,
		&i.SignPublicKey,
		&i.WrappedByPassword,
		&i.SaltPw,
		&i.WrappedByPhrase,
		&i.SaltRp,
		&i.KdfParams,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
