// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: connected_devices.sql

package db

import (
	"context"
	"time"
)

const countConnectedDevices = `-- name: CountConnectedDevices :one
SELECT
    COUNT(*)
FROM
    connected_devices
`

func (q *Queries) CountConnectedDevices(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countConnectedDevices)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteConnectedDevice = `-- name: DeleteConnectedDevice :exec
DELETE FROM connected_devices
WHERE
    id = ?
`

func (q *Queries) DeleteConnectedDevice(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteConnectedDevice, id)
	return err
}

const getConnectedDevice = `-- name: GetConnectedDevice :one
SELECT
    id, ip_address, user_agent, first_seen_at, last_seen_at, request_count
FROM
    connected_devices
WHERE
    id = ?
LIMIT
    1
`

func (q *Queries) GetConnectedDevice(ctx context.Context, id int64) (ConnectedDevice, error) {
	row := q.db.QueryRowContext(ctx, getConnectedDevice, id)
	var i ConnectedDevice
	err := row.Scan(
		&i.ID,
		&i.IpAddress,
		&i.UserAgent,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.RequestCount,
	)
	return i, err
}

const listConnectedDevices = `-- name: ListConnectedDevices :many
SELECT
    id, ip_address, user_agent, first_seen_at, last_seen_at, request_count
FROM
    connected_devices
ORDER BY
    last_seen_at DESC
`

func (q *Queries) ListConnectedDevices(ctx context.Context) ([]ConnectedDevice, error) {
	rows, err := q.db.QueryContext(ctx, listConnectedDevices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConnectedDevice
	for rows.Next() {
		var i ConnectedDevice
		if err := rows.Scan(
			&i.ID,
			&i.IpAddress,
			&i.UserAgent,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.RequestCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneConnectedDevices = `-- name: PruneConnectedDevices :execrows
DELETE FROM connected_devices
WHERE
    connected_devices.last_seen_at < ?1
    OR connected_devices.id NOT IN (
        SELECT
            newest.id
        FROM
            connected_devices AS newest
        ORDER BY
            newest.last_seen_at DESC,
            newest.id DESC
        LIMIT
            ?2
    )
`

type PruneConnectedDevicesParams struct {
	Cutoff time.Time
	Keep   int64
}

// Drops peers not seen since the cutoff, and every peer past the newest keep
// by last_seen_at, so the table holds at most keep rows (#2756).
func (q *Queries) PruneConnectedDevices(ctx context.Context, arg PruneConnectedDevicesParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, pruneConnectedDevices, arg.Cutoff, arg.Keep)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertConnectedDevice = `-- name: UpsertConnectedDevice :one
INSERT INTO
    connected_devices (ip_address, user_agent, first_seen_at, last_seen_at, request_count)
VALUES
    (?, ?, datetime('now'), datetime('now'), 1)
ON CONFLICT (ip_address, user_agent) DO UPDATE SET
    last_seen_at = datetime('now'),
    request_count = request_count + 1
RETURNING id, ip_address, user_agent, first_seen_at, last_seen_at, request_count
`

type UpsertConnectedDeviceParams struct {
	IpAddress string
	UserAgent string
}

func (q *Queries) UpsertConnectedDevice(ctx context.Context, arg UpsertConnectedDeviceParams) (ConnectedDevice, error) {
	row := q.db.QueryRowContext(ctx, upsertConnectedDevice, arg.IpAddress, arg.UserAgent)
	var i ConnectedDevice
	err := row.Scan(
		&i.ID,
		&i.IpAddress,
		&i.UserAgent,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.RequestCount,
	)
	return i, err
}
