// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: groups.sql

package db

import (
	"context"
)

const addGroupMember = `-- name: AddGroupMember :execrows
INSERT INTO group_members (group_id, user_id) VALUES (?, ?) ON CONFLICT DO NOTHING
`

type AddGroupMemberParams struct {
	GroupID int64
	UserID  int64
}

// AddGroupMember puts an account in a group. Adding a member again changes
// nothing and reports no rows.
func (q *Queries) AddGroupMember(ctx context.Context, arg AddGroupMemberParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, addGroupMember, arg.GroupID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (name) VALUES (?) RETURNING id, name, builtin
`

func (q *Queries) CreateGroup(ctx context.Context, name string) (Group, error) {
	row := q.db.QueryRowContext(ctx, createGroup, name)
	var i Group
	err := row.Scan(&i.ID, &i.Name, &i.Builtin)
	return i, err
}

const deleteGroup = `-- name: DeleteGroup :execrows
DELETE FROM groups WHERE id = ? AND builtin = 0
`

// DeleteGroup drops a group; ON DELETE CASCADE drops its members and grants.
func (q *Queries) DeleteGroup(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteGroup, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getGroup = `-- name: GetGroup :one
SELECT id, name, builtin FROM groups WHERE id = ? LIMIT 1
`

func (q *Queries) GetGroup(ctx context.Context, id int64) (Group, error) {
	row := q.db.QueryRowContext(ctx, getGroup, id)
	var i Group
	err := row.Scan(&i.ID, &i.Name, &i.Builtin)
	return i, err
}

const listGroupMembers = `-- name: ListGroupMembers :many
SELECT
    group_members.group_id,
    users.id AS user_id,
    users.username
FROM
    group_members
    JOIN users ON users.id = group_members.user_id
ORDER BY
    users.username
`

type ListGroupMembersRow struct {
	GroupID  int64
	UserID   int64
	Username string
}

// ListGroupMembers lists every membership with the member's username, for
// ListGroups to fold into its groups.
func (q *Queries) ListGroupMembers(ctx context.Context) ([]ListGroupMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, listGroupMembers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGroupMembersRow
	for rows.Next() {
		var i ListGroupMembersRow
		if err := rows.Scan(&i.GroupID, &i.UserID, &i.Username); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroups = `-- name: ListGroups :many

SELECT id, name, builtin FROM groups ORDER BY builtin DESC, name COLLATE NOCASE, id
`

// Groups an admin manages (#1910). The built-in everyone group is seeded by
// 010_path_access; the builtin = 0 guards keep every change away from it.
func (q *Queries) ListGroups(ctx context.Context) ([]Group, error) {
	rows, err := q.db.QueryContext(ctx, listGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Group
	for rows.Next() {
		var i Group
		if err := rows.Scan(&i.ID, &i.Name, &i.Builtin); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeGroupMember = `-- name: RemoveGroupMember :execrows
DELETE FROM group_members WHERE group_id = ? AND user_id = ?
`

type RemoveGroupMemberParams struct {
	GroupID int64
	UserID  int64
}

func (q *Queries) RemoveGroupMember(ctx context.Context, arg RemoveGroupMemberParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, removeGroupMember, arg.GroupID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const renameGroup = `-- name: RenameGroup :one
UPDATE groups SET name = ? WHERE id = ? AND builtin = 0 RETURNING id, name, builtin
`

type RenameGroupParams struct {
	Name string
	ID   int64
}

func (q *Queries) RenameGroup(ctx context.Context, arg RenameGroupParams) (Group, error) {
	row := q.db.QueryRowContext(ctx, renameGroup, arg.Name, arg.ID)
	var i Group
	err := row.Scan(&i.ID, &i.Name, &i.Builtin)
	return i, err
}
