// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: install.sql

package db

import (
	"context"
)

const getInstallID = `-- name: GetInstallID :one
SELECT install_id FROM install WHERE id = 1
`

func (q *Queries) GetInstallID(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, getInstallID)
	var install_id string
	err := row.Scan(&install_id)
	return install_id, err
}

const rotateInstallID = `-- name: RotateInstallID :exec
UPDATE install SET install_id = lower(hex(randomblob(16))) WHERE id = 1
`

// For a reset that leaves the database standing (files or devices only): the
// other instances still have to drop what they hold for the wiped install.
func (q *Queries) RotateInstallID(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, rotateInstallID)
	return err
}
