// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package db

import (
	"context"
	"database/sql"
	"strings"
)

const cancelJob = `-- name: CancelJob :one
UPDATE jobs
SET
    status = 'canceled',
    finished_at = datetime('now')
WHERE
    id = ?
    AND status IN ('pending', 'running')
RETURNING id, kind, name, status, params, progress, lane, attempts, error, created_at, started_at, finished_at, user_id, detail, owner, heartbeat_at
`

func (q *Queries) CancelJob(ctx context.Context, id int64) (Job, error) {
	row := q.db.QueryRowContext(ctx, cancelJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.Status,
		&i.Params,
		&i.Progress,
		&i.Lane,
		&i.Attempts,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.UserID,
		&i.Detail,
		&i.Owner,
		&i.HeartbeatAt,
	)
	return i, err
}

const claimJob = `-- name: ClaimJob :one
UPDATE jobs
SET
    status = 'running',
    attempts = attempts + 1,
    started_at = datetime('now'),
    owner = ?1,
    heartbeat_at = datetime('now')
WHERE
    jobs.id = ?2
    AND jobs.status = 'pending'
    AND (
        SELECT
            COUNT(*)
        FROM
            jobs AS busy
        WHERE
            busy.status = 'running'
            AND busy.kind = jobs.kind
            AND busy.lane = jobs.lane
    ) < CAST(?3 AS INTEGER)
RETURNING id, kind, name, status, params, progress, lane, attempts, error, created_at, started_at, finished_at, user_id, detail, owner, heartbeat_at
`

type ClaimJobParams struct {
	Owner     string
	ID        int64
	LaneLimit int64
}

// Claims a pending job for an instance (#2966). The status guard makes a job
// canceled or claimed by another instance since it was picked match no row,
// and so does the lane count, which is what holds a lane's limit across
// instances. The count is exact on SQLite, which has one writer at a time.
// PostgreSQL at READ COMMITTED lets two claims count before either commits,
// so that backend has to serialize claims per lane when it lands.
func (q *Queries) ClaimJob(ctx context.Context, arg ClaimJobParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, claimJob, arg.Owner, arg.ID, arg.LaneLimit)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.Status,
		&i.Params,
		&i.Progress,
		&i.Lane,
		&i.Attempts,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.UserID,
		&i.Detail,
		&i.Owner,
		&i.HeartbeatAt,
	)
	return i, err
}

const createJob = `-- name: CreateJob :one
INSERT INTO
    jobs (kind, name, params, lane, user_id)
VALUES
    (?, ?, ?, ?, ?)
RETURNING id, kind, name, status, params, progress, lane, attempts, error, created_at, started_at, finished_at, user_id, detail, owner, heartbeat_at
`

type CreateJobParams struct {
	Kind   string
	Name   string
	Params string
	Lane   string
	UserID sql.NullInt64
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, createJob,
		arg.Kind,
		arg.Name,
		arg.Params,
		arg.Lane,
		arg.UserID,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.Status,
		&i.Params,
		&i.Progress,
		&i.Lane,
		&i.Attempts,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.UserID,
		&i.Detail,
		&i.Owner,
		&i.HeartbeatAt,
	)
	return i, err
}

const failExhaustedStaleJobs = `-- name: FailExhaustedStaleJobs :many
UPDATE jobs
SET
    status = 'failed',
    error = ?1,
    finished_at = datetime('now')
WHERE
    status = 'running'
    AND attempts >= ?2
    AND (
        heartbeat_at IS NULL
        OR heartbeat_at < datetime('now', '-' || CAST(?3 AS INTEGER) || ' seconds')
    )
RETURNING id, kind, name, status, params, progress, lane, attempts, error, created_at, started_at, finished_at, user_id, detail, owner, heartbeat_at
`

type FailExhaustedStaleJobsParams struct {
	Reason       string
	MaxAttempts  int64
	LeaseSeconds int64
}

// A running job whose owner has not beaten for lease_seconds belongs to an
// instance that is gone. The database's clock is on both sides of the
// comparison, so instances need not agree on the time. One that has already
// started max_attempts times fails here, so a job that kills its process does
// not do it forever; run this before RequeueStaleJobs.
func (q *Queries) FailExhaustedStaleJobs(ctx context.Context, arg FailExhaustedStaleJobsParams) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, failExhaustedStaleJobs, arg.Reason, arg.MaxAttempts, arg.LeaseSeconds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Name,
			&i.Status,
			&i.Params,
			&i.Progress,
			&i.Lane,
			&i.Attempts,
			&i.Error,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.UserID,
			&i.Detail,
			&i.Owner,
			&i.HeartbeatAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const finishJob = `-- name: FinishJob :one
UPDATE jobs
SET
    status = ?,
    error = ?,
    progress = ?,
    finished_at = datetime('now')
WHERE
    id = ?
    AND status = 'running'
    AND owner = ?
RETURNING id, kind, name, status, params, progress, lane, attempts, error, created_at, started_at, finished_at, user_id, detail, owner, heartbeat_at
`

type FinishJobParams struct {
	Status   string
	Error    string
	Progress float64
	ID       int64
	Owner    string
}

// Only a running job is finished here, so a job canceled while its handler
// was still unwinding keeps the canceled status Cancel gave it, and only by
// its owner, so a reclaimed job is settled by the instance that reran it.
func (q *Queries) FinishJob(ctx context.Context, arg FinishJobParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, finishJob,
		arg.Status,
		arg.Error,
		arg.Progress,
		arg.ID,
		arg.Owner,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.Status,
		&i.Params,
		&i.Progress,
		&i.Lane,
		&i.Attempts,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.UserID,
		&i.Detail,
		&i.Owner,
		&i.HeartbeatAt,
	)
	return i, err
}

const getActiveBackupJob = `-- name: GetActiveBackupJob :one
SELECT
    id, kind, name, status, params, progress, lane, attempts, error, created_at, started_at, finished_at, user_id, detail, owner, heartbeat_at
FROM
    jobs
WHERE
    kind = 'snapshot-backup'
    AND status IN ('pending', 'running')
    AND json_extract(params, '$.targetDeviceSerial') = CAST(?1 AS TEXT)
LIMIT
    1
`

// The backup holding a target device's lock (#3084): idx_jobs_backup_target
// allows one pending or running snapshot backup per target.
func (q *Queries) GetActiveBackupJob(ctx context.Context, targetDeviceSerial string) (Job, error) {
	row := q.db.QueryRowContext(ctx, getActiveBackupJob, targetDeviceSerial)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.Status,
		&i.Params,
		&i.Progress,
		&i.Lane,
		&i.Attempts,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.UserID,
		&i.Detail,
		&i.Owner,
		&i.HeartbeatAt,
	)
	return i, err
}

const getJob = `-- name: GetJob :one
SELECT
    id, kind, name, status, params, progress, lane, attempts, error, created_at, started_at, finished_at, user_id, detail, owner, heartbeat_at
FROM
    jobs
WHERE
    id = ?
LIMIT
    1
`

func (q *Queries) GetJob(ctx context.Context, id int64) (Job, error) {
	row := q.db.QueryRowContext(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.Status,
		&i.Params,
		&i.Progress,
		&i.Lane,
		&i.Attempts,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.UserID,
		&i.Detail,
		&i.Owner,
		&i.HeartbeatAt,
	)
	return i, err
}

const heartbeatJobs = `-- name: HeartbeatJobs :many
UPDATE jobs
SET
    heartbeat_at = datetime('now')
WHERE
    owner = ?
    AND status = 'running'
RETURNING id
`

// An instance's heartbeat: every job it is still running, which it compares
// with what it has in memory to learn of one canceled or reclaimed elsewhere.
func (q *Queries) HeartbeatJobs(ctx context.Context, owner string) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, heartbeatJobs, owner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobs = `-- name: ListJobs :many
SELECT
    id, kind, name, status, params, progress, lane, attempts, error, created_at, started_at, finished_at, user_id, detail, owner, heartbeat_at
FROM
    jobs
WHERE
    kind IN (/*SLICE:kinds*/?)
ORDER BY
    id DESC
`

func (q *Queries) ListJobs(ctx context.Context, kinds []string) ([]Job, error) {
	query := listJobs
	var queryParams []interface{}
	if len(kinds) > 0 {
		for _, v := range kinds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:kinds*/?", strings.Repeat(",?", len(kinds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:kinds*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Name,
			&i.Status,
			&i.Params,
			&i.Progress,
			&i.Lane,
			&i.Attempts,
			&i.Error,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.UserID,
			&i.Detail,
			&i.Owner,
			&i.HeartbeatAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingJobs = `-- name: ListPendingJobs :many
SELECT
    id,
    kind,
    lane
FROM
    jobs
WHERE
    status = 'pending'
ORDER BY
    id
`

type ListPendingJobsRow struct {
	ID   int64
	Kind string
	Lane string
}

// The pending jobs, oldest first, for the dispatcher to pick from by lane.
func (q *Queries) ListPendingJobs(ctx context.Context) ([]ListPendingJobsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPendingJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingJobsRow
	for rows.Next() {
		var i ListPendingJobsRow
		if err := rows.Scan(&i.ID, &i.Kind, &i.Lane); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserJobs = `-- name: ListUserJobs :many
SELECT
    id, kind, name, status, params, progress, lane, attempts, error, created_at, started_at, finished_at, user_id, detail, owner, heartbeat_at
FROM
    jobs
WHERE
    user_id = ?1
    AND kind IN (/*SLICE:kinds*/?)
ORDER BY
    id DESC
`

type ListUserJobsParams struct {
	UserID sql.NullInt64
	Kinds  []string
}

// ListJobs for one account, so a non-admin's listing never loads every other
// account's jobs (#2756).
func (q *Queries) ListUserJobs(ctx context.Context, arg ListUserJobsParams) ([]Job, error) {
	query := listUserJobs
	var queryParams []interface{}
	queryParams = append(queryParams, arg.UserID)
	if len(arg.Kinds) > 0 {
		for _, v := range arg.Kinds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:kinds*/?", strings.Repeat(",?", len(arg.Kinds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:kinds*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Name,
			&i.Status,
			&i.Params,
			&i.Progress,
			&i.Lane,
			&i.Attempts,
			&i.Error,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.UserID,
			&i.Detail,
			&i.Owner,
			&i.HeartbeatAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneFinishedJobs = `-- name: PruneFinishedJobs :execrows
DELETE FROM jobs
WHERE
    jobs.status IN ('completed', 'failed', 'canceled')
    AND (
        jobs.finished_at < ?1
        OR jobs.id <= (
            SELECT
                newer.id
            FROM
                jobs AS newer
            WHERE
                newer.status IN ('completed', 'failed', 'canceled')
                AND newer.user_id IS jobs.user_id
            ORDER BY
                newer.id DESC
            LIMIT
                1
            OFFSET
                ?2
        )
    )
`

type PruneFinishedJobsParams struct {
	Cutoff sql.NullTime
	Keep   int64
}

// Drops finished jobs that finished before the cutoff, and every finished job
// past each owner's newest keep, so job history is bounded per account
// (#2756). Pending and running jobs are never touched.
func (q *Queries) PruneFinishedJobs(ctx context.Context, arg PruneFinishedJobsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, pruneFinishedJobs, arg.Cutoff, arg.Keep)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const releaseJob = `-- name: ReleaseJob :one
UPDATE jobs
SET
    status = 'pending',
    progress = 0,
    owner = '',
    heartbeat_at = NULL,
    started_at = NULL
WHERE
    id = ?
    AND status = 'running'
    AND owner = ?
RETURNING id, kind, name, status, params, progress, lane, attempts, error, created_at, started_at, finished_at, user_id, detail, owner, heartbeat_at
`

type ReleaseJobParams struct {
	ID    int64
	Owner string
}

// Puts a job its owner was running back in the queue, for an instance that
// is shutting down: another one, or this one's next start, runs it again.
func (q *Queries) ReleaseJob(ctx context.Context, arg ReleaseJobParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, releaseJob, arg.ID, arg.Owner)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.Status,
		&i.Params,
		&i.Progress,
		&i.Lane,
		&i.Attempts,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.UserID,
		&i.Detail,
		&i.Owner,
		&i.HeartbeatAt,
	)
	return i, err
}

const requeueStaleJobs = `-- name: RequeueStaleJobs :many
UPDATE jobs
SET
    status = 'pending',
    progress = 0,
    owner = '',
    heartbeat_at = NULL,
    started_at = NULL
WHERE
    status = 'running'
    AND (
        heartbeat_at IS NULL
        OR heartbeat_at < datetime('now', '-' || CAST(?1 AS INTEGER) || ' seconds')
    )
RETURNING id, kind, name, status, params, progress, lane, attempts, error, created_at, started_at, finished_at, user_id, detail, owner, heartbeat_at
`

// Every other running job whose owner stopped beating goes back in the queue
// for any instance to run.
func (q *Queries) RequeueStaleJobs(ctx context.Context, leaseSeconds int64) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, requeueStaleJobs, leaseSeconds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Name,
			&i.Status,
			&i.Params,
			&i.Progress,
			&i.Lane,
			&i.Attempts,
			&i.Error,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.UserID,
			&i.Detail,
			&i.Owner,
			&i.HeartbeatAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retryJob = `-- name: RetryJob :one
UPDATE jobs
SET
    status = 'pending',
    lane = ?,
    progress = 0,
    error = '',
    started_at = NULL,
    finished_at = NULL
WHERE
    id = ?
    AND status = 'failed'
RETURNING id, kind, name, status, params, progress, lane, attempts, error, created_at, started_at, finished_at, user_id, detail, owner, heartbeat_at
`

type RetryJobParams struct {
	Lane string
	ID   int64
}

// Resets a failed job so it runs again, in the lane its kind picked again.
// The status guard makes a second, racing retry match no row. created_at is
// left alone.
func (q *Queries) RetryJob(ctx context.Context, arg RetryJobParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, retryJob, arg.Lane, arg.ID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.Status,
		&i.Params,
		&i.Progress,
		&i.Lane,
		&i.Attempts,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.UserID,
		&i.Detail,
		&i.Owner,
		&i.HeartbeatAt,
	)
	return i, err
}

const updateJobDetail = `-- name: UpdateJobDetail :exec
UPDATE jobs
SET
    detail = ?
WHERE
    id = ?
    AND status = 'running'
`

type UpdateJobDetailParams struct {
	Detail string
	ID     int64
}

// The status guard keeps a job finished or canceled since from being touched.
func (q *Queries) UpdateJobDetail(ctx context.Context, arg UpdateJobDetailParams) error {
	_, err := q.db.ExecContext(ctx, updateJobDetail, arg.Detail, arg.ID)
	return err
}

const updateJobProgress = `-- name: UpdateJobProgress :execrows
UPDATE jobs
SET
    progress = ?
WHERE
    id = ?
    AND status = 'running'
    AND owner = ?
`

type UpdateJobProgressParams struct {
	Progress float64
	ID       int64
	Owner    string
}

// The owner guard keeps an instance whose job was reclaimed from writing to a
// run that is no longer its own.
func (q *Queries) UpdateJobProgress(ctx context.Context, arg UpdateJobProgressParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateJobProgress, arg.Progress, arg.ID, arg.Owner)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
