// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package db

import (
	"context"
	"database/sql"
	"strings"
)

const cancelJob = `-- name: CancelJob :one
UPDATE jobs
SET
    status = 'canceled',
    finished_at = datetime('now')
WHERE
    id = ?
    AND status IN ('pending', 'running')
RETURNING id, kind, name, status, params, progress, lane, attempts, error, created_at, started_at, finished_at, user_id
`

func (q *Queries) CancelJob(ctx context.Context, id int64) (Job, error) {
	row := q.db.QueryRowContext(ctx, cancelJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.Status,
		&i.Params,
		&i.Progress,
		&i.Lane,
		&i.Attempts,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.UserID,
	)
	return i, err
}

const claimJob = `-- name: ClaimJob :one
UPDATE jobs
SET
    status = 'running',
    attempts = attempts + 1,
    started_at = datetime('now')
WHERE
    id = ?
    AND status = 'pending'
RETURNING id, kind, name, status, params, progress, lane, attempts, error, created_at, started_at, finished_at, user_id
`

// The status guard makes a job canceled since it was picked match no row.
func (q *Queries) ClaimJob(ctx context.Context, id int64) (Job, error) {
	row := q.db.QueryRowContext(ctx, claimJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.Status,
		&i.Params,
		&i.Progress,
		&i.Lane,
		&i.Attempts,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.UserID,
	)
	return i, err
}

const createJob = `-- name: CreateJob :one
INSERT INTO
    jobs (kind, name, params, lane, user_id)
VALUES
    (?, ?, ?, ?, ?)
RETURNING id, kind, name, status, params, progress, lane, attempts, error, created_at, started_at, finished_at, user_id
`

type CreateJobParams struct {
	Kind   string
	Name   string
	Params string
	Lane   string
	UserID sql.NullInt64
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, createJob,
		arg.Kind,
		arg.Name,
		arg.Params,
		arg.Lane,
		arg.UserID,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.Status,
		&i.Params,
		&i.Progress,
		&i.Lane,
		&i.Attempts,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.UserID,
	)
	return i, err
}

const finishJob = `-- name: FinishJob :one
UPDATE jobs
SET
    status = ?,
    error = ?,
    progress = ?,
    finished_at = datetime('now')
WHERE
    id = ?
    AND status = 'running'
RETURNING id, kind, name, status, params, progress, lane, attempts, error, created_at, started_at, finished_at, user_id
`

type FinishJobParams struct {
	Status   string
	Error    string
	Progress float64
	ID       int64
}

// Only a running job is finished here, so a job canceled while its handler
// was still unwinding keeps the canceled status Cancel gave it.
func (q *Queries) FinishJob(ctx context.Context, arg FinishJobParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, finishJob,
		arg.Status,
		arg.Error,
		arg.Progress,
		arg.ID,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.Status,
		&i.Params,
		&i.Progress,
		&i.Lane,
		&i.Attempts,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.UserID,
	)
	return i, err
}

const getJob = `-- name: GetJob :one
SELECT
    id, kind, name, status, params, progress, lane, attempts, error, created_at, started_at, finished_at, user_id
FROM
    jobs
WHERE
    id = ?
LIMIT
    1
`

func (q *Queries) GetJob(ctx context.Context, id int64) (Job, error) {
	row := q.db.QueryRowContext(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.Status,
		&i.Params,
		&i.Progress,
		&i.Lane,
		&i.Attempts,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.UserID,
	)
	return i, err
}

const interruptRunningJobs = `-- name: InterruptRunningJobs :exec
UPDATE jobs
SET
    status = 'failed',
    error = ?1,
    finished_at = datetime('now')
WHERE
    status = 'running'
`

// Rows still running when a process starts belong to one that is gone.
func (q *Queries) InterruptRunningJobs(ctx context.Context, reason string) error {
	_, err := q.db.ExecContext(ctx, interruptRunningJobs, reason)
	return err
}

const listJobs = `-- name: ListJobs :many
SELECT
    id, kind, name, status, params, progress, lane, attempts, error, created_at, started_at, finished_at, user_id
FROM
    jobs
WHERE
    kind IN (/*SLICE:kinds*/?)
ORDER BY
    id DESC
`

func (q *Queries) ListJobs(ctx context.Context, kinds []string) ([]Job, error) {
	query := listJobs
	var queryParams []interface{}
	if len(kinds) > 0 {
		for _, v := range kinds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:kinds*/?", strings.Repeat(",?", len(kinds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:kinds*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Name,
			&i.Status,
			&i.Params,
			&i.Progress,
			&i.Lane,
			&i.Attempts,
			&i.Error,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingJobs = `-- name: ListPendingJobs :many
SELECT
    id,
    kind,
    lane
FROM
    jobs
WHERE
    status = 'pending'
ORDER BY
    id
`

type ListPendingJobsRow struct {
	ID   int64
	Kind string
	Lane string
}

// The pending jobs, oldest first, for the dispatcher to pick from by lane.
func (q *Queries) ListPendingJobs(ctx context.Context) ([]ListPendingJobsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPendingJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingJobsRow
	for rows.Next() {
		var i ListPendingJobsRow
		if err := rows.Scan(&i.ID, &i.Kind, &i.Lane); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retryJob = `-- name: RetryJob :one
UPDATE jobs
SET
    status = 'pending',
    lane = ?,
    progress = 0,
    error = '',
    started_at = NULL,
    finished_at = NULL
WHERE
    id = ?
    AND status = 'failed'
RETURNING id, kind, name, status, params, progress, lane, attempts, error, created_at, started_at, finished_at, user_id
`

type RetryJobParams struct {
	Lane string
	ID   int64
}

// Resets a failed job so it runs again, in the lane its kind picked again.
// The status guard makes a second, racing retry match no row. created_at is
// left alone.
func (q *Queries) RetryJob(ctx context.Context, arg RetryJobParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, retryJob, arg.Lane, arg.ID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.Status,
		&i.Params,
		&i.Progress,
		&i.Lane,
		&i.Attempts,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.UserID,
	)
	return i, err
}

const updateJobProgress = `-- name: UpdateJobProgress :execrows
UPDATE jobs
SET
    progress = ?
WHERE
    id = ?
    AND status = 'running'
`

type UpdateJobProgressParams struct {
	Progress float64
	ID       int64
}

func (q *Queries) UpdateJobProgress(ctx context.Context, arg UpdateJobProgressParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateJobProgress, arg.Progress, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
