// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: maintenance.sql

package db

import (
	"context"
)

const claimMaintenanceRun = `-- name: ClaimMaintenanceRun :execrows
UPDATE maintenance_runs
SET
    owner = ?1,
    started_at = datetime('now')
WHERE
    name = ?2
    AND started_at <= datetime('now', '-' || CAST(?3 AS INTEGER) || ' seconds')
`

type ClaimMaintenanceRunParams struct {
	Owner           string
	Name            string
	IntervalSeconds int64
}

// Takes a periodic task's turn (#2966): the row is written only when the task
// last started at least interval_seconds ago, so of the instances ticking on
// one database exactly one changes a row per interval. The database's clock
// is on both sides of the comparison, so instances need not agree on the
// time.
func (q *Queries) ClaimMaintenanceRun(ctx context.Context, arg ClaimMaintenanceRunParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, claimMaintenanceRun, arg.Owner, arg.Name, arg.IntervalSeconds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const ensureMaintenanceRun = `-- name: EnsureMaintenanceRun :exec
INSERT INTO
    maintenance_runs (name, owner, started_at)
VALUES
    (?, '', datetime('now', '-100 years'))
ON CONFLICT (name) DO NOTHING
`

// Makes sure a periodic task has a row for ClaimMaintenanceRun to take, dated
// so that a task that has never run is due.
func (q *Queries) EnsureMaintenanceRun(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, ensureMaintenanceRun, name)
	return err
}
