// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type ConnectedDevice struct {
	ID           int64
	IpAddress    string
	UserAgent    string
	FirstSeenAt  time.Time
	LastSeenAt   time.Time
	RequestCount int64
}

type DeviceName struct {
	DeviceSerial string
	DisplayName  string
	UpdatedAt    time.Time
}

type DeviceRole struct {
	DeviceSerial string
	Role         string
	UpdatedAt    time.Time
}

type FileContent struct {
	ID        int64
	Serial    string
	RelPath   string
	Extracted string
	UpdatedAt time.Time
}

type FileContentFt struct {
	Extracted string
}

type PhotoAlbum struct {
	ID            int64
	Name          string
	ParentID      sql.NullInt64
	CreatedAt     time.Time
	UpdatedAt     time.Time
	SmartType     sql.NullString
	RetentionDays sql.NullInt64
}

type PhotoAlbumItem struct {
	ID           int64
	AlbumID      int64
	DeviceSerial string
	RelPath      string
	AddedAt      time.Time
}

type PhotoFavorite struct {
	ID           int64
	DeviceSerial string
	RelPath      string
	CreatedAt    time.Time
}

type PhotoHash struct {
	ID           int64
	DeviceSerial string
	RelPath      string
	Dhash        sql.NullString
	ContentHash  sql.NullString
	ComputedAt   time.Time
}

type PhotoRotation struct {
	ID               int64
	DeviceSerial     string
	RelPath          string
	RotationQuarters int64
	UpdatedAt        time.Time
}

type Session struct {
	Token     string
	UserID    int64
	ExpiresAt time.Time
	CreatedAt time.Time
}

type User struct {
	ID                 int64
	Username           string
	PasswordHash       string
	RecoveryPhraseHash string
	CreatedAt          time.Time
	IsAdmin            int64
}

type VaultConfig struct {
	ID                int64
	Salt              []byte
	Argon2Memory      int64
	Argon2Iterations  int64
	Argon2Parallelism int64
	VerificationBlob  []byte
	VerificationNonce []byte
	AutoLockSeconds   int64
	CreatedAt         time.Time
}

type VaultEntry struct {
	ID         int64
	Name       string
	UrlHost    string
	FolderID   sql.NullInt64
	Ciphertext []byte
	Nonce      []byte
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type VaultFolder struct {
	ID        int64
	Name      string
	ParentID  sql.NullInt64
	SortOrder int64
	CreatedAt time.Time
}

type VaultLocation struct {
	ID           int64
	DeviceSerial string
	UpdatedAt    time.Time
}

type VfsDbEntry struct {
	ID        int64
	Namespace string
	Path      string
	IsDir     bool
	Size      int64
	MimeType  string
	Content   []byte
	CreatedAt time.Time
	UpdatedAt time.Time
}

type VfsMetadatum struct {
	ID        int64
	Namespace string
	Path      string
	Key       string
	Value     string
	UpdatedAt time.Time
}

type VideoJob struct {
	ID            int64
	JobType       string
	Status        string
	DeviceSerial  string
	InputRelPath  string
	OutputRelPath string
	Params        string
	Progress      float64
	ErrorMessage  string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}
