// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: photo_albums.sql

package db

import (
	"context"
	"database/sql"
)

const addPhotoToAlbum = `-- name: AddPhotoToAlbum :one
INSERT INTO
    photo_album_items (album_id, device_serial, rel_path)
VALUES
    (?, ?, ?)
ON CONFLICT (album_id, device_serial, rel_path) DO UPDATE
SET
    added_at = added_at -- no-op; keeps RETURNING from returning nothing
RETURNING id, album_id, device_serial, rel_path, added_at
`

type AddPhotoToAlbumParams struct {
	AlbumID      int64
	DeviceSerial string
	RelPath      string
}

func (q *Queries) AddPhotoToAlbum(ctx context.Context, arg AddPhotoToAlbumParams) (PhotoAlbumItem, error) {
	row := q.db.QueryRowContext(ctx, addPhotoToAlbum, arg.AlbumID, arg.DeviceSerial, arg.RelPath)
	var i PhotoAlbumItem
	err := row.Scan(
		&i.ID,
		&i.AlbumID,
		&i.DeviceSerial,
		&i.RelPath,
		&i.AddedAt,
	)
	return i, err
}

const countAlbumItems = `-- name: CountAlbumItems :one
SELECT
    COUNT(*)
FROM
    photo_album_items
WHERE
    album_id = ?
`

func (q *Queries) CountAlbumItems(ctx context.Context, albumID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAlbumItems, albumID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAlbum = `-- name: CreateAlbum :one
INSERT INTO
    photo_albums (name, parent_id, user_id)
VALUES
    (
        ?1,
        ?2,
        CAST(?3 AS INTEGER)
    )
RETURNING id, name, parent_id, created_at, updated_at, smart_type, user_id
`

type CreateAlbumParams struct {
	Name     string
	ParentID sql.NullInt64
	UserID   int64
}

func (q *Queries) CreateAlbum(ctx context.Context, arg CreateAlbumParams) (PhotoAlbum, error) {
	row := q.db.QueryRowContext(ctx, createAlbum, arg.Name, arg.ParentID, arg.UserID)
	var i PhotoAlbum
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SmartType,
		&i.UserID,
	)
	return i, err
}

const deleteAlbum = `-- name: DeleteAlbum :exec
DELETE FROM photo_albums
WHERE
    id = ?1
    AND user_id = CAST(?2 AS INTEGER)
`

type DeleteAlbumParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteAlbum(ctx context.Context, arg DeleteAlbumParams) error {
	_, err := q.db.ExecContext(ctx, deleteAlbum, arg.ID, arg.UserID)
	return err
}

const deletePhotoFromAllAlbums = `-- name: DeletePhotoFromAllAlbums :exec
DELETE FROM photo_album_items
WHERE
    device_serial = ?1
    AND (
        rel_path = ?2
        OR substr(rel_path, 1, length(?2) + 1) = ?2 || '/'
    )
`

type DeletePhotoFromAllAlbumsParams struct {
	DeviceSerial string
	RelPath      string
}

// DeletePhotoFromAllAlbums drops every album row for the path, and for
// everything under it when the path is a folder. substr rather than LIKE, so a
// '%' or '_' in a file name is not a wildcard.
func (q *Queries) DeletePhotoFromAllAlbums(ctx context.Context, arg DeletePhotoFromAllAlbumsParams) error {
	_, err := q.db.ExecContext(ctx, deletePhotoFromAllAlbums, arg.DeviceSerial, arg.RelPath)
	return err
}

const getAlbum = `-- name: GetAlbum :one
SELECT
    id, name, parent_id, created_at, updated_at, smart_type, user_id
FROM
    photo_albums
WHERE
    id = ?1
    AND user_id = CAST(?2 AS INTEGER)
LIMIT
    1
`

type GetAlbumParams struct {
	ID     int64
	UserID int64
}

// Album reads and writes are scoped to the owning account (#1912): another
// account's album id reads as missing. The CAST keeps the nullable user_id
// column (014) a plain id parameter.
func (q *Queries) GetAlbum(ctx context.Context, arg GetAlbumParams) (PhotoAlbum, error) {
	row := q.db.QueryRowContext(ctx, getAlbum, arg.ID, arg.UserID)
	var i PhotoAlbum
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SmartType,
		&i.UserID,
	)
	return i, err
}

const listAlbumItems = `-- name: ListAlbumItems :many
SELECT
    id, album_id, device_serial, rel_path, added_at
FROM
    photo_album_items
WHERE
    album_id = ?
ORDER BY
    added_at DESC
`

func (q *Queries) ListAlbumItems(ctx context.Context, albumID int64) ([]PhotoAlbumItem, error) {
	rows, err := q.db.QueryContext(ctx, listAlbumItems, albumID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PhotoAlbumItem
	for rows.Next() {
		var i PhotoAlbumItem
		if err := rows.Scan(
			&i.ID,
			&i.AlbumID,
			&i.DeviceSerial,
			&i.RelPath,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlbums = `-- name: ListAlbums :many
SELECT
    id, name, parent_id, created_at, updated_at, smart_type, user_id
FROM
    photo_albums
WHERE
    user_id = CAST(?1 AS INTEGER)
ORDER BY
    parent_id,
    name
`

func (q *Queries) ListAlbums(ctx context.Context, userID int64) ([]PhotoAlbum, error) {
	rows, err := q.db.QueryContext(ctx, listAlbums, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PhotoAlbum
	for rows.Next() {
		var i PhotoAlbum
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ParentID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SmartType,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlbumsContainingPhoto = `-- name: ListAlbumsContainingPhoto :many
SELECT
    pa.id, pa.name, pa.parent_id, pa.created_at, pa.updated_at, pa.smart_type, pa.user_id
FROM
    photo_albums pa
    JOIN photo_album_items pai ON pa.id = pai.album_id
WHERE
    pa.user_id = CAST(?1 AS INTEGER)
    AND pai.device_serial = ?2
    AND pai.rel_path = ?3
ORDER BY
    pa.name
`

type ListAlbumsContainingPhotoParams struct {
	UserID       int64
	DeviceSerial string
	RelPath      string
}

// ListAlbumsContainingPhoto lists the albums of one account that hold a photo.
func (q *Queries) ListAlbumsContainingPhoto(ctx context.Context, arg ListAlbumsContainingPhotoParams) ([]PhotoAlbum, error) {
	rows, err := q.db.QueryContext(ctx, listAlbumsContainingPhoto, arg.UserID, arg.DeviceSerial, arg.RelPath)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PhotoAlbum
	for rows.Next() {
		var i PhotoAlbum
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ParentID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SmartType,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChildAlbums = `-- name: ListChildAlbums :many
SELECT
    id, name, parent_id, created_at, updated_at, smart_type, user_id
FROM
    photo_albums
WHERE
    parent_id = ?
ORDER BY
    name
`

func (q *Queries) ListChildAlbums(ctx context.Context, parentID sql.NullInt64) ([]PhotoAlbum, error) {
	rows, err := q.db.QueryContext(ctx, listChildAlbums, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PhotoAlbum
	for rows.Next() {
		var i PhotoAlbum
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ParentID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SmartType,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRootAlbums = `-- name: ListRootAlbums :many
SELECT
    id, name, parent_id, created_at, updated_at, smart_type, user_id
FROM
    photo_albums
WHERE
    user_id = CAST(?1 AS INTEGER)
    AND parent_id IS NULL
ORDER BY
    name
`

func (q *Queries) ListRootAlbums(ctx context.Context, userID int64) ([]PhotoAlbum, error) {
	rows, err := q.db.QueryContext(ctx, listRootAlbums, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PhotoAlbum
	for rows.Next() {
		var i PhotoAlbum
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ParentID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SmartType,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveAlbum = `-- name: MoveAlbum :one
UPDATE photo_albums
SET
    parent_id = ?1,
    updated_at = datetime('now')
WHERE
    id = ?2
    AND user_id = CAST(?3 AS INTEGER)
RETURNING id, name, parent_id, created_at, updated_at, smart_type, user_id
`

type MoveAlbumParams struct {
	ParentID sql.NullInt64
	ID       int64
	UserID   int64
}

func (q *Queries) MoveAlbum(ctx context.Context, arg MoveAlbumParams) (PhotoAlbum, error) {
	row := q.db.QueryRowContext(ctx, moveAlbum, arg.ParentID, arg.ID, arg.UserID)
	var i PhotoAlbum
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SmartType,
		&i.UserID,
	)
	return i, err
}

const moveAlbumItems = `-- name: MoveAlbumItems :exec
UPDATE OR IGNORE photo_album_items
SET
    device_serial = ?1,
    rel_path = ?2 || substr(rel_path, length(CAST(?3 AS TEXT)) + 1)
WHERE
    device_serial = ?4
    AND (
        rel_path = ?3
        OR substr(rel_path, 1, length(?3) + 1) = ?3 || '/'
    )
`

type MoveAlbumItemsParams struct {
	NewDeviceSerial string
	NewRelPath      string
	OldRelPath      string
	OldDeviceSerial string
}

// MoveAlbumItems points album rows at a moved file, or at everything under a
// moved folder. OR IGNORE skips a row whose destination the album already
// holds; DeletePhotoFromAllAlbums on the old path clears those leftovers.
func (q *Queries) MoveAlbumItems(ctx context.Context, arg MoveAlbumItemsParams) error {
	_, err := q.db.ExecContext(ctx, moveAlbumItems,
		arg.NewDeviceSerial,
		arg.NewRelPath,
		arg.OldRelPath,
		arg.OldDeviceSerial,
	)
	return err
}

const removePhotoFromAlbum = `-- name: RemovePhotoFromAlbum :exec
DELETE FROM photo_album_items
WHERE
    album_id = ?
    AND device_serial = ?
    AND rel_path = ?
`

type RemovePhotoFromAlbumParams struct {
	AlbumID      int64
	DeviceSerial string
	RelPath      string
}

func (q *Queries) RemovePhotoFromAlbum(ctx context.Context, arg RemovePhotoFromAlbumParams) error {
	_, err := q.db.ExecContext(ctx, removePhotoFromAlbum, arg.AlbumID, arg.DeviceSerial, arg.RelPath)
	return err
}

const renameAlbum = `-- name: RenameAlbum :one
UPDATE photo_albums
SET
    name = ?1,
    updated_at = datetime('now')
WHERE
    id = ?2
    AND user_id = CAST(?3 AS INTEGER)
RETURNING id, name, parent_id, created_at, updated_at, smart_type, user_id
`

type RenameAlbumParams struct {
	Name   string
	ID     int64
	UserID int64
}

func (q *Queries) RenameAlbum(ctx context.Context, arg RenameAlbumParams) (PhotoAlbum, error) {
	row := q.db.QueryRowContext(ctx, renameAlbum, arg.Name, arg.ID, arg.UserID)
	var i PhotoAlbum
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SmartType,
		&i.UserID,
	)
	return i, err
}
