// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: photo_favorites.sql

package db

import (
	"context"
)

const addFavorite = `-- name: AddFavorite :exec
INSERT INTO
    photo_favorites (device_serial, rel_path)
VALUES
    (?, ?)
ON CONFLICT (device_serial, rel_path) DO NOTHING
`

type AddFavoriteParams struct {
	DeviceSerial string
	RelPath      string
}

func (q *Queries) AddFavorite(ctx context.Context, arg AddFavoriteParams) error {
	_, err := q.db.ExecContext(ctx, addFavorite, arg.DeviceSerial, arg.RelPath)
	return err
}

const createFavoritesAlbum = `-- name: CreateFavoritesAlbum :one
INSERT INTO
    photo_albums (name, smart_type)
VALUES
    ('Favorites', 'favorites')
RETURNING id, name, parent_id, created_at, updated_at, smart_type
`

func (q *Queries) CreateFavoritesAlbum(ctx context.Context) (PhotoAlbum, error) {
	row := q.db.QueryRowContext(ctx, createFavoritesAlbum)
	var i PhotoAlbum
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SmartType,
	)
	return i, err
}

const deleteFavoritesUnder = `-- name: DeleteFavoritesUnder :exec
DELETE FROM photo_favorites
WHERE
    device_serial = ?1
    AND (
        rel_path = ?2
        OR substr(rel_path, 1, length(?2) + 1) = ?2 || '/'
    )
`

type DeleteFavoritesUnderParams struct {
	DeviceSerial string
	RelPath      string
}

// DeleteFavoritesUnder drops the favorite for a deleted path, and every
// favorite under it when the path is a folder.
func (q *Queries) DeleteFavoritesUnder(ctx context.Context, arg DeleteFavoritesUnderParams) error {
	_, err := q.db.ExecContext(ctx, deleteFavoritesUnder, arg.DeviceSerial, arg.RelPath)
	return err
}

const getFavoritesAlbum = `-- name: GetFavoritesAlbum :one
SELECT
    id, name, parent_id, created_at, updated_at, smart_type
FROM
    photo_albums
WHERE
    smart_type = 'favorites'
LIMIT
    1
`

func (q *Queries) GetFavoritesAlbum(ctx context.Context) (PhotoAlbum, error) {
	row := q.db.QueryRowContext(ctx, getFavoritesAlbum)
	var i PhotoAlbum
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SmartType,
	)
	return i, err
}

const isFavorite = `-- name: IsFavorite :one
SELECT
    COUNT(*) > 0
FROM
    photo_favorites
WHERE
    device_serial = ?
    AND rel_path = ?
`

type IsFavoriteParams struct {
	DeviceSerial string
	RelPath      string
}

func (q *Queries) IsFavorite(ctx context.Context, arg IsFavoriteParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isFavorite, arg.DeviceSerial, arg.RelPath)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const listFavorites = `-- name: ListFavorites :many
SELECT
    id, device_serial, rel_path, created_at
FROM
    photo_favorites
ORDER BY
    created_at DESC
`

func (q *Queries) ListFavorites(ctx context.Context) ([]PhotoFavorite, error) {
	rows, err := q.db.QueryContext(ctx, listFavorites)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PhotoFavorite
	for rows.Next() {
		var i PhotoFavorite
		if err := rows.Scan(
			&i.ID,
			&i.DeviceSerial,
			&i.RelPath,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveFavorites = `-- name: MoveFavorites :exec
UPDATE OR IGNORE photo_favorites
SET
    device_serial = ?1,
    rel_path = ?2 || substr(rel_path, length(CAST(?3 AS TEXT)) + 1)
WHERE
    device_serial = ?4
    AND (
        rel_path = ?3
        OR substr(rel_path, 1, length(?3) + 1) = ?3 || '/'
    )
`

type MoveFavoritesParams struct {
	NewDeviceSerial string
	NewRelPath      string
	OldRelPath      string
	OldDeviceSerial string
}

// MoveFavorites points favorites at a moved file or folder. OR IGNORE skips
// a row whose destination is already a favorite; DeleteFavoritesUnder on the
// old path clears those leftovers.
func (q *Queries) MoveFavorites(ctx context.Context, arg MoveFavoritesParams) error {
	_, err := q.db.ExecContext(ctx, moveFavorites,
		arg.NewDeviceSerial,
		arg.NewRelPath,
		arg.OldRelPath,
		arg.OldDeviceSerial,
	)
	return err
}

const removeFavorite = `-- name: RemoveFavorite :exec
DELETE FROM photo_favorites
WHERE
    device_serial = ?
    AND rel_path = ?
`

type RemoveFavoriteParams struct {
	DeviceSerial string
	RelPath      string
}

func (q *Queries) RemoveFavorite(ctx context.Context, arg RemoveFavoriteParams) error {
	_, err := q.db.ExecContext(ctx, removeFavorite, arg.DeviceSerial, arg.RelPath)
	return err
}
