// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: photo_hashes.sql

package db

import (
	"context"
	"database/sql"
)

const deletePhotoHash = `-- name: DeletePhotoHash :exec
DELETE FROM photo_hashes
WHERE device_serial = ? AND rel_path = ?
`

type DeletePhotoHashParams struct {
	DeviceSerial string
	RelPath      string
}

// DeletePhotoHash drops the hashes of one photo that is no longer on disk.
func (q *Queries) DeletePhotoHash(ctx context.Context, arg DeletePhotoHashParams) error {
	_, err := q.db.ExecContext(ctx, deletePhotoHash, arg.DeviceSerial, arg.RelPath)
	return err
}

const deletePhotoHashesUnder = `-- name: DeletePhotoHashesUnder :exec
DELETE FROM photo_hashes
WHERE
    device_serial = ?1
    AND (
        rel_path = ?2
        OR substr(rel_path, 1, length(?2) + 1) = ?2 || '/'
    )
`

type DeletePhotoHashesUnderParams struct {
	DeviceSerial string
	RelPath      string
}

// DeletePhotoHashesUnder drops the hashes of a deleted or moved path, and of
// everything under it when the path is a folder.
func (q *Queries) DeletePhotoHashesUnder(ctx context.Context, arg DeletePhotoHashesUnderParams) error {
	_, err := q.db.ExecContext(ctx, deletePhotoHashesUnder, arg.DeviceSerial, arg.RelPath)
	return err
}

const listExactDuplicates = `-- name: ListExactDuplicates :many
SELECT content_hash, device_serial, rel_path
FROM photo_hashes
WHERE content_hash IS NOT NULL
  AND content_hash IN (
      SELECT content_hash FROM photo_hashes
      WHERE content_hash IS NOT NULL
      GROUP BY content_hash HAVING COUNT(*) > 1
  )
ORDER BY content_hash, device_serial, rel_path
`

type ListExactDuplicatesRow struct {
	ContentHash  sql.NullString
	DeviceSerial string
	RelPath      string
}

func (q *Queries) ListExactDuplicates(ctx context.Context) ([]ListExactDuplicatesRow, error) {
	rows, err := q.db.QueryContext(ctx, listExactDuplicates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExactDuplicatesRow
	for rows.Next() {
		var i ListExactDuplicatesRow
		if err := rows.Scan(&i.ContentHash, &i.DeviceSerial, &i.RelPath); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNearDuplicates = `-- name: ListNearDuplicates :many
SELECT dhash, content_hash, device_serial, rel_path
FROM photo_hashes
WHERE dhash IS NOT NULL
ORDER BY dhash, device_serial, rel_path
`

type ListNearDuplicatesRow struct {
	Dhash        sql.NullString
	ContentHash  sql.NullString
	DeviceSerial string
	RelPath      string
}

func (q *Queries) ListNearDuplicates(ctx context.Context) ([]ListNearDuplicatesRow, error) {
	rows, err := q.db.QueryContext(ctx, listNearDuplicates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNearDuplicatesRow
	for rows.Next() {
		var i ListNearDuplicatesRow
		if err := rows.Scan(
			&i.Dhash,
			&i.ContentHash,
			&i.DeviceSerial,
			&i.RelPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPhotoHashStates = `-- name: ListPhotoHashStates :many
SELECT device_serial, rel_path, dhash, content_hash IS NOT NULL AS has_content_hash, taken_checked
FROM photo_hashes
`

type ListPhotoHashStatesRow struct {
	DeviceSerial   string
	RelPath        string
	Dhash          sql.NullString
	HasContentHash bool
	TakenChecked   bool
}

// ListPhotoHashStates reports what is stored for every photo, for the
// backfill to find what is missing.
func (q *Queries) ListPhotoHashStates(ctx context.Context) ([]ListPhotoHashStatesRow, error) {
	rows, err := q.db.QueryContext(ctx, listPhotoHashStates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPhotoHashStatesRow
	for rows.Next() {
		var i ListPhotoHashStatesRow
		if err := rows.Scan(
			&i.DeviceSerial,
			&i.RelPath,
			&i.Dhash,
			&i.HasContentHash,
			&i.TakenChecked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPhotoTakenAt = `-- name: ListPhotoTakenAt :many
SELECT device_serial, rel_path, taken_at
FROM photo_hashes
WHERE taken_at IS NOT NULL
`

type ListPhotoTakenAtRow struct {
	DeviceSerial string
	RelPath      string
	TakenAt      sql.NullTime
}

// ListPhotoTakenAt returns every capture date known, for the date-taken sort.
func (q *Queries) ListPhotoTakenAt(ctx context.Context) ([]ListPhotoTakenAtRow, error) {
	rows, err := q.db.QueryContext(ctx, listPhotoTakenAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPhotoTakenAtRow
	for rows.Next() {
		var i ListPhotoTakenAtRow
		if err := rows.Scan(&i.DeviceSerial, &i.RelPath, &i.TakenAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPhotoTakenAt = `-- name: SetPhotoTakenAt :exec
UPDATE photo_hashes
SET taken_at = ?, taken_checked = 1
WHERE device_serial = ? AND rel_path = ?
`

type SetPhotoTakenAtParams struct {
	TakenAt      sql.NullTime
	DeviceSerial string
	RelPath      string
}

// SetPhotoTakenAt records the capture date of a photo whose hashes are
// already stored (#2592).
func (q *Queries) SetPhotoTakenAt(ctx context.Context, arg SetPhotoTakenAtParams) error {
	_, err := q.db.ExecContext(ctx, setPhotoTakenAt, arg.TakenAt, arg.DeviceSerial, arg.RelPath)
	return err
}

const upsertPhotoHash = `-- name: UpsertPhotoHash :exec
INSERT INTO photo_hashes (device_serial, rel_path, dhash, content_hash, taken_at, taken_checked)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT (device_serial, rel_path)
DO UPDATE SET
    dhash         = excluded.dhash,
    content_hash  = excluded.content_hash,
    taken_at      = CASE WHEN excluded.taken_checked THEN excluded.taken_at ELSE photo_hashes.taken_at END,
    taken_checked = photo_hashes.taken_checked OR excluded.taken_checked,
    computed_at   = datetime('now')
`

type UpsertPhotoHashParams struct {
	DeviceSerial string
	RelPath      string
	Dhash        sql.NullString
	ContentHash  sql.NullString
	TakenAt      sql.NullTime
	TakenChecked bool
}

// UpsertPhotoHash stores a photo's hashes, and its capture date when
// taken_checked says the EXIF was read. A write that did not read it keeps
// the date already stored.
func (q *Queries) UpsertPhotoHash(ctx context.Context, arg UpsertPhotoHashParams) error {
	_, err := q.db.ExecContext(ctx, upsertPhotoHash,
		arg.DeviceSerial,
		arg.RelPath,
		arg.Dhash,
		arg.ContentHash,
		arg.TakenAt,
		arg.TakenChecked,
	)
	return err
}
