// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: settings.sql

package db

import (
	"context"
	"time"
)

const addAccountRequestDecision = `-- name: AddAccountRequestDecision :exec
INSERT INTO account_request_history (username, outcome, decided_by, decided_at)
VALUES (?, ?, ?, ?)
ON CONFLICT DO NOTHING
`

type AddAccountRequestDecisionParams struct {
	Username  string
	Outcome   string
	DecidedBy string
	DecidedAt time.Time
}

func (q *Queries) AddAccountRequestDecision(ctx context.Context, arg AddAccountRequestDecisionParams) error {
	_, err := q.db.ExecContext(ctx, addAccountRequestDecision,
		arg.Username,
		arg.Outcome,
		arg.DecidedBy,
		arg.DecidedAt,
	)
	return err
}

const addSetting = `-- name: AddSetting :exec
INSERT INTO settings (key, value) VALUES (?, ?)
ON CONFLICT (key) DO NOTHING
`

type AddSettingParams struct {
	Key   string
	Value string
}

// Keeps a value already there: for the salt secret two instances may both try
// to create, and for the import of settings.json.
func (q *Queries) AddSetting(ctx context.Context, arg AddSettingParams) error {
	_, err := q.db.ExecContext(ctx, addSetting, arg.Key, arg.Value)
	return err
}

const addUserSettings = `-- name: AddUserSettings :exec
INSERT INTO user_settings (user_id, settings)
SELECT u.id, ?1 FROM users u WHERE u.id = ?2
ON CONFLICT (user_id) DO NOTHING
`

type AddUserSettingsParams struct {
	Settings string
	UserID   int64
}

// For the import of user-settings/: keeps settings already there, and skips a
// file whose account is gone.
func (q *Queries) AddUserSettings(ctx context.Context, arg AddUserSettingsParams) error {
	_, err := q.db.ExecContext(ctx, addUserSettings, arg.Settings, arg.UserID)
	return err
}

const getSetting = `-- name: GetSetting :one
SELECT value FROM settings WHERE key = ?
`

func (q *Queries) GetSetting(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getSetting, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const getUserSettings = `-- name: GetUserSettings :one
SELECT settings FROM user_settings WHERE user_id = ?
`

func (q *Queries) GetUserSettings(ctx context.Context, userID int64) (string, error) {
	row := q.db.QueryRowContext(ctx, getUserSettings, userID)
	var settings string
	err := row.Scan(&settings)
	return settings, err
}

const listAccountRequestHistory = `-- name: ListAccountRequestHistory :many
SELECT username, outcome, decided_by, decided_at
FROM account_request_history
ORDER BY id DESC
LIMIT ?
`

type ListAccountRequestHistoryRow struct {
	Username  string
	Outcome   string
	DecidedBy string
	DecidedAt time.Time
}

func (q *Queries) ListAccountRequestHistory(ctx context.Context, limit int64) ([]ListAccountRequestHistoryRow, error) {
	rows, err := q.db.QueryContext(ctx, listAccountRequestHistory, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAccountRequestHistoryRow
	for rows.Next() {
		var i ListAccountRequestHistoryRow
		if err := rows.Scan(
			&i.Username,
			&i.Outcome,
			&i.DecidedBy,
			&i.DecidedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSettings = `-- name: ListSettings :many
SELECT key, value FROM settings
`

func (q *Queries) ListSettings(ctx context.Context) ([]Setting, error) {
	rows, err := q.db.QueryContext(ctx, listSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Setting
	for rows.Next() {
		var i Setting
		if err := rows.Scan(&i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSetting = `-- name: SetSetting :exec
INSERT INTO settings (key, value) VALUES (?, ?)
ON CONFLICT (key) DO UPDATE SET value = excluded.value
`

type SetSettingParams struct {
	Key   string
	Value string
}

func (q *Queries) SetSetting(ctx context.Context, arg SetSettingParams) error {
	_, err := q.db.ExecContext(ctx, setSetting, arg.Key, arg.Value)
	return err
}

const setUserSettings = `-- name: SetUserSettings :exec
INSERT INTO user_settings (user_id, settings) VALUES (?, ?)
ON CONFLICT (user_id) DO UPDATE SET settings = excluded.settings
`

type SetUserSettingsParams struct {
	UserID   int64
	Settings string
}

func (q *Queries) SetUserSettings(ctx context.Context, arg SetUserSettingsParams) error {
	_, err := q.db.ExecContext(ctx, setUserSettings, arg.UserID, arg.Settings)
	return err
}

const trimAccountRequestHistory = `-- name: TrimAccountRequestHistory :exec
DELETE FROM account_request_history
WHERE id NOT IN (SELECT id FROM account_request_history ORDER BY id DESC LIMIT ?)
`

func (q *Queries) TrimAccountRequestHistory(ctx context.Context, limit int64) error {
	_, err := q.db.ExecContext(ctx, trimAccountRequestHistory, limit)
	return err
}
