// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: vault.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createVaultConfig = `-- name: CreateVaultConfig :exec
INSERT INTO vault_config (
    id, salt, argon2_memory, argon2_iterations, argon2_parallelism,
    verification_blob, verification_nonce, auto_lock_seconds
) VALUES (1, ?, ?, ?, ?, ?, ?, ?)
`

type CreateVaultConfigParams struct {
	Salt              []byte
	Argon2Memory      int64
	Argon2Iterations  int64
	Argon2Parallelism int64
	VerificationBlob  []byte
	VerificationNonce []byte
	AutoLockSeconds   int64
}

func (q *Queries) CreateVaultConfig(ctx context.Context, arg CreateVaultConfigParams) error {
	_, err := q.db.ExecContext(ctx, createVaultConfig,
		arg.Salt,
		arg.Argon2Memory,
		arg.Argon2Iterations,
		arg.Argon2Parallelism,
		arg.VerificationBlob,
		arg.VerificationNonce,
		arg.AutoLockSeconds,
	)
	return err
}

const createVaultEntry = `-- name: CreateVaultEntry :one
INSERT INTO vault_entries (name, url_host, folder_id, ciphertext, nonce)
VALUES (?, ?, ?, ?, ?)
RETURNING id, name, url_host, folder_id, ciphertext, nonce, created_at, updated_at
`

type CreateVaultEntryParams struct {
	Name       string
	UrlHost    string
	FolderID   sql.NullInt64
	Ciphertext []byte
	Nonce      []byte
}

func (q *Queries) CreateVaultEntry(ctx context.Context, arg CreateVaultEntryParams) (VaultEntry, error) {
	row := q.db.QueryRowContext(ctx, createVaultEntry,
		arg.Name,
		arg.UrlHost,
		arg.FolderID,
		arg.Ciphertext,
		arg.Nonce,
	)
	var i VaultEntry
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UrlHost,
		&i.FolderID,
		&i.Ciphertext,
		&i.Nonce,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createVaultFolder = `-- name: CreateVaultFolder :one
INSERT INTO vault_folders (name, parent_id, sort_order)
VALUES (?, ?, ?)
RETURNING id, name, parent_id, sort_order, created_at
`

type CreateVaultFolderParams struct {
	Name      string
	ParentID  sql.NullInt64
	SortOrder int64
}

func (q *Queries) CreateVaultFolder(ctx context.Context, arg CreateVaultFolderParams) (VaultFolder, error) {
	row := q.db.QueryRowContext(ctx, createVaultFolder, arg.Name, arg.ParentID, arg.SortOrder)
	var i VaultFolder
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ParentID,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const deleteVaultEntry = `-- name: DeleteVaultEntry :exec
DELETE FROM vault_entries WHERE id = ?
`

func (q *Queries) DeleteVaultEntry(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteVaultEntry, id)
	return err
}

const deleteVaultFolder = `-- name: DeleteVaultFolder :exec
DELETE FROM vault_folders WHERE id = ?
`

func (q *Queries) DeleteVaultFolder(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteVaultFolder, id)
	return err
}

const getVaultConfig = `-- name: GetVaultConfig :one
SELECT id, salt, argon2_memory, argon2_iterations, argon2_parallelism, verification_blob, verification_nonce, auto_lock_seconds, created_at FROM vault_config WHERE id = 1
`

func (q *Queries) GetVaultConfig(ctx context.Context) (VaultConfig, error) {
	row := q.db.QueryRowContext(ctx, getVaultConfig)
	var i VaultConfig
	err := row.Scan(
		&i.ID,
		&i.Salt,
		&i.Argon2Memory,
		&i.Argon2Iterations,
		&i.Argon2Parallelism,
		&i.VerificationBlob,
		&i.VerificationNonce,
		&i.AutoLockSeconds,
		&i.CreatedAt,
	)
	return i, err
}

const getVaultEntry = `-- name: GetVaultEntry :one
SELECT id, name, url_host, folder_id, ciphertext, nonce, created_at, updated_at FROM vault_entries WHERE id = ?
`

func (q *Queries) GetVaultEntry(ctx context.Context, id int64) (VaultEntry, error) {
	row := q.db.QueryRowContext(ctx, getVaultEntry, id)
	var i VaultEntry
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UrlHost,
		&i.FolderID,
		&i.Ciphertext,
		&i.Nonce,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVaultFolder = `-- name: GetVaultFolder :one
SELECT id, name, parent_id, sort_order, created_at FROM vault_folders WHERE id = ?
`

func (q *Queries) GetVaultFolder(ctx context.Context, id int64) (VaultFolder, error) {
	row := q.db.QueryRowContext(ctx, getVaultFolder, id)
	var i VaultFolder
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ParentID,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const listAllVaultEntriesForReEncrypt = `-- name: ListAllVaultEntriesForReEncrypt :many
SELECT id, ciphertext, nonce FROM vault_entries
`

type ListAllVaultEntriesForReEncryptRow struct {
	ID         int64
	Ciphertext []byte
	Nonce      []byte
}

func (q *Queries) ListAllVaultEntriesForReEncrypt(ctx context.Context) ([]ListAllVaultEntriesForReEncryptRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllVaultEntriesForReEncrypt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllVaultEntriesForReEncryptRow
	for rows.Next() {
		var i ListAllVaultEntriesForReEncryptRow
		if err := rows.Scan(&i.ID, &i.Ciphertext, &i.Nonce); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVaultEntries = `-- name: ListVaultEntries :many
SELECT id, name, url_host, folder_id, created_at, updated_at
FROM vault_entries
ORDER BY name
`

type ListVaultEntriesRow struct {
	ID        int64
	Name      string
	UrlHost   string
	FolderID  sql.NullInt64
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) ListVaultEntries(ctx context.Context) ([]ListVaultEntriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listVaultEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVaultEntriesRow
	for rows.Next() {
		var i ListVaultEntriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.UrlHost,
			&i.FolderID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVaultEntriesWithoutHost = `-- name: ListVaultEntriesWithoutHost :many
SELECT id, ciphertext, nonce FROM vault_entries WHERE url_host = ''
`

type ListVaultEntriesWithoutHostRow struct {
	ID         int64
	Ciphertext []byte
	Nonce      []byte
}

func (q *Queries) ListVaultEntriesWithoutHost(ctx context.Context) ([]ListVaultEntriesWithoutHostRow, error) {
	rows, err := q.db.QueryContext(ctx, listVaultEntriesWithoutHost)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVaultEntriesWithoutHostRow
	for rows.Next() {
		var i ListVaultEntriesWithoutHostRow
		if err := rows.Scan(&i.ID, &i.Ciphertext, &i.Nonce); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVaultFolders = `-- name: ListVaultFolders :many
SELECT id, name, parent_id, sort_order, created_at FROM vault_folders ORDER BY sort_order, name
`

func (q *Queries) ListVaultFolders(ctx context.Context) ([]VaultFolder, error) {
	rows, err := q.db.QueryContext(ctx, listVaultFolders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VaultFolder
	for rows.Next() {
		var i VaultFolder
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ParentID,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVaultConfigPassword = `-- name: UpdateVaultConfigPassword :exec
UPDATE vault_config
SET salt = ?, verification_blob = ?, verification_nonce = ?
WHERE id = 1
`

type UpdateVaultConfigPasswordParams struct {
	Salt              []byte
	VerificationBlob  []byte
	VerificationNonce []byte
}

func (q *Queries) UpdateVaultConfigPassword(ctx context.Context, arg UpdateVaultConfigPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateVaultConfigPassword, arg.Salt, arg.VerificationBlob, arg.VerificationNonce)
	return err
}

const updateVaultEntry = `-- name: UpdateVaultEntry :exec
UPDATE vault_entries
SET name = ?, url_host = ?, folder_id = ?, ciphertext = ?, nonce = ?,
    updated_at = datetime('now')
WHERE id = ?
`

type UpdateVaultEntryParams struct {
	Name       string
	UrlHost    string
	FolderID   sql.NullInt64
	Ciphertext []byte
	Nonce      []byte
	ID         int64
}

func (q *Queries) UpdateVaultEntry(ctx context.Context, arg UpdateVaultEntryParams) error {
	_, err := q.db.ExecContext(ctx, updateVaultEntry,
		arg.Name,
		arg.UrlHost,
		arg.FolderID,
		arg.Ciphertext,
		arg.Nonce,
		arg.ID,
	)
	return err
}

const updateVaultEntryCiphertext = `-- name: UpdateVaultEntryCiphertext :exec
UPDATE vault_entries
SET ciphertext = ?, nonce = ?, updated_at = datetime('now')
WHERE id = ?
`

type UpdateVaultEntryCiphertextParams struct {
	Ciphertext []byte
	Nonce      []byte
	ID         int64
}

func (q *Queries) UpdateVaultEntryCiphertext(ctx context.Context, arg UpdateVaultEntryCiphertextParams) error {
	_, err := q.db.ExecContext(ctx, updateVaultEntryCiphertext, arg.Ciphertext, arg.Nonce, arg.ID)
	return err
}

const updateVaultEntryHost = `-- name: UpdateVaultEntryHost :exec
UPDATE vault_entries SET url_host = ? WHERE id = ?
`

type UpdateVaultEntryHostParams struct {
	UrlHost string
	ID      int64
}

func (q *Queries) UpdateVaultEntryHost(ctx context.Context, arg UpdateVaultEntryHostParams) error {
	_, err := q.db.ExecContext(ctx, updateVaultEntryHost, arg.UrlHost, arg.ID)
	return err
}

const updateVaultFolder = `-- name: UpdateVaultFolder :exec
UPDATE vault_folders
SET name = ?, parent_id = ?, sort_order = ?
WHERE id = ?
`

type UpdateVaultFolderParams struct {
	Name      string
	ParentID  sql.NullInt64
	SortOrder int64
	ID        int64
}

func (q *Queries) UpdateVaultFolder(ctx context.Context, arg UpdateVaultFolderParams) error {
	_, err := q.db.ExecContext(ctx, updateVaultFolder,
		arg.Name,
		arg.ParentID,
		arg.SortOrder,
		arg.ID,
	)
	return err
}
