// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: vfs.sql

package db

import (
	"context"
	"time"
)

const countDBVFSEntriesUnder = `-- name: CountDBVFSEntriesUnder :one
SELECT
    COUNT(1)
FROM
    vfs_db_entries
WHERE
    namespace = ?1
    AND substr(path, 1, length(CAST(?2 AS TEXT))) = CAST(?2 AS TEXT)
    AND path != ?3
`

type CountDBVFSEntriesUnderParams struct {
	Namespace string
	Prefix    string
	Dir       string
}

func (q *Queries) CountDBVFSEntriesUnder(ctx context.Context, arg CountDBVFSEntriesUnderParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDBVFSEntriesUnder, arg.Namespace, arg.Prefix, arg.Dir)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteDBVFSEntry = `-- name: DeleteDBVFSEntry :execrows
DELETE FROM vfs_db_entries
WHERE
    namespace = ?
    AND path = ?
`

type DeleteDBVFSEntryParams struct {
	Namespace string
	Path      string
}

func (q *Queries) DeleteDBVFSEntry(ctx context.Context, arg DeleteDBVFSEntryParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteDBVFSEntry, arg.Namespace, arg.Path)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteDBVFSEntryTree = `-- name: DeleteDBVFSEntryTree :execrows
DELETE FROM vfs_db_entries
WHERE
    namespace = ?1
    AND (
        path = ?2
        OR substr(path, 1, length(CAST(?3 AS TEXT))) = CAST(?3 AS TEXT)
    )
`

type DeleteDBVFSEntryTreeParams struct {
	Namespace string
	Path      string
	Prefix    string
}

func (q *Queries) DeleteDBVFSEntryTree(ctx context.Context, arg DeleteDBVFSEntryTreeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteDBVFSEntryTree, arg.Namespace, arg.Path, arg.Prefix)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteVFSMetadataKey = `-- name: DeleteVFSMetadataKey :exec
DELETE FROM vfs_metadata
WHERE
    namespace = ?
    AND path = ?
    AND key = ?
`

type DeleteVFSMetadataKeyParams struct {
	Namespace string
	Path      string
	Key       string
}

func (q *Queries) DeleteVFSMetadataKey(ctx context.Context, arg DeleteVFSMetadataKeyParams) error {
	_, err := q.db.ExecContext(ctx, deleteVFSMetadataKey, arg.Namespace, arg.Path, arg.Key)
	return err
}

const getDBVFSEntry = `-- name: GetDBVFSEntry :one
SELECT
    is_dir,
    size,
    mime_type,
    updated_at
FROM
    vfs_db_entries
WHERE
    namespace = ?
    AND path = ?
`

type GetDBVFSEntryParams struct {
	Namespace string
	Path      string
}

type GetDBVFSEntryRow struct {
	IsDir     bool
	Size      int64
	MimeType  string
	UpdatedAt time.Time
}

func (q *Queries) GetDBVFSEntry(ctx context.Context, arg GetDBVFSEntryParams) (GetDBVFSEntryRow, error) {
	row := q.db.QueryRowContext(ctx, getDBVFSEntry, arg.Namespace, arg.Path)
	var i GetDBVFSEntryRow
	err := row.Scan(
		&i.IsDir,
		&i.Size,
		&i.MimeType,
		&i.UpdatedAt,
	)
	return i, err
}

const getDBVFSEntryContent = `-- name: GetDBVFSEntryContent :one
SELECT
    is_dir,
    content
FROM
    vfs_db_entries
WHERE
    namespace = ?
    AND path = ?
`

type GetDBVFSEntryContentParams struct {
	Namespace string
	Path      string
}

type GetDBVFSEntryContentRow struct {
	IsDir   bool
	Content []byte
}

func (q *Queries) GetDBVFSEntryContent(ctx context.Context, arg GetDBVFSEntryContentParams) (GetDBVFSEntryContentRow, error) {
	row := q.db.QueryRowContext(ctx, getDBVFSEntryContent, arg.Namespace, arg.Path)
	var i GetDBVFSEntryContentRow
	err := row.Scan(&i.IsDir, &i.Content)
	return i, err
}

const insertDBVFSDirIfAbsent = `-- name: InsertDBVFSDirIfAbsent :exec
INSERT OR IGNORE INTO
    vfs_db_entries (namespace, path, is_dir, size, mime_type, content)
VALUES
    (?, ?, 1, 0, '', NULL)
`

type InsertDBVFSDirIfAbsentParams struct {
	Namespace string
	Path      string
}

func (q *Queries) InsertDBVFSDirIfAbsent(ctx context.Context, arg InsertDBVFSDirIfAbsentParams) error {
	_, err := q.db.ExecContext(ctx, insertDBVFSDirIfAbsent, arg.Namespace, arg.Path)
	return err
}

const insertDBVFSFileIfAbsent = `-- name: InsertDBVFSFileIfAbsent :execrows
INSERT INTO
    vfs_db_entries (namespace, path, is_dir, size, mime_type, content, updated_at)
VALUES
    (?, ?, 0, ?, ?, ?, datetime('now'))
ON CONFLICT (namespace, path) DO NOTHING
`

type InsertDBVFSFileIfAbsentParams struct {
	Namespace string
	Path      string
	Size      int64
	MimeType  string
	Content   []byte
}

// Anything already at the path is left alone and reports no rows.
func (q *Queries) InsertDBVFSFileIfAbsent(ctx context.Context, arg InsertDBVFSFileIfAbsentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertDBVFSFileIfAbsent,
		arg.Namespace,
		arg.Path,
		arg.Size,
		arg.MimeType,
		arg.Content,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listDBVFSEntriesUnder = `-- name: ListDBVFSEntriesUnder :many
SELECT
    path,
    is_dir,
    size,
    mime_type,
    updated_at
FROM
    vfs_db_entries
WHERE
    namespace = ?1
    AND substr(path, 1, length(CAST(?2 AS TEXT))) = CAST(?2 AS TEXT)
    AND path != ?3
ORDER BY
    path
`

type ListDBVFSEntriesUnderParams struct {
	Namespace string
	Prefix    string
	Dir       string
}

type ListDBVFSEntriesUnderRow struct {
	Path      string
	IsDir     bool
	Size      int64
	MimeType  string
	UpdatedAt time.Time
}

func (q *Queries) ListDBVFSEntriesUnder(ctx context.Context, arg ListDBVFSEntriesUnderParams) ([]ListDBVFSEntriesUnderRow, error) {
	rows, err := q.db.QueryContext(ctx, listDBVFSEntriesUnder, arg.Namespace, arg.Prefix, arg.Dir)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDBVFSEntriesUnderRow
	for rows.Next() {
		var i ListDBVFSEntriesUnderRow
		if err := rows.Scan(
			&i.Path,
			&i.IsDir,
			&i.Size,
			&i.MimeType,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVFSMetadata = `-- name: ListVFSMetadata :many

SELECT
    key,
    value
FROM
    vfs_metadata
WHERE
    namespace = ?
    AND path = ?
`

type ListVFSMetadataParams struct {
	Namespace string
	Path      string
}

type ListVFSMetadataRow struct {
	Key   string
	Value string
}

// Queries behind pkg/vfs: vfs_metadata (SQLiteMetadataStore) and
// vfs_db_entries (DBVFS).
//
// A descendant of a directory is matched with substr rather than LIKE, so a
// '%' or '_' in a name is not a wildcard. prefix is "dir/", and its length is
// taken here because substr counts characters where Go's len counts bytes.
func (q *Queries) ListVFSMetadata(ctx context.Context, arg ListVFSMetadataParams) ([]ListVFSMetadataRow, error) {
	rows, err := q.db.QueryContext(ctx, listVFSMetadata, arg.Namespace, arg.Path)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVFSMetadataRow
	for rows.Next() {
		var i ListVFSMetadataRow
		if err := rows.Scan(&i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVFSMetadataPathsByKey = `-- name: ListVFSMetadataPathsByKey :many
SELECT
    path
FROM
    vfs_metadata
WHERE
    namespace = ?
    AND key = ?
ORDER BY
    path
`

type ListVFSMetadataPathsByKeyParams struct {
	Namespace string
	Key       string
}

func (q *Queries) ListVFSMetadataPathsByKey(ctx context.Context, arg ListVFSMetadataPathsByKeyParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listVFSMetadataPathsByKey, arg.Namespace, arg.Key)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var path string
		if err := rows.Scan(&path); err != nil {
			return nil, err
		}
		items = append(items, path)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVFSMetadataPathsByKeyValue = `-- name: ListVFSMetadataPathsByKeyValue :many
SELECT
    path
FROM
    vfs_metadata
WHERE
    namespace = ?
    AND key = ?
    AND value = ?
ORDER BY
    path
`

type ListVFSMetadataPathsByKeyValueParams struct {
	Namespace string
	Key       string
	Value     string
}

func (q *Queries) ListVFSMetadataPathsByKeyValue(ctx context.Context, arg ListVFSMetadataPathsByKeyValueParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listVFSMetadataPathsByKeyValue, arg.Namespace, arg.Key, arg.Value)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var path string
		if err := rows.Scan(&path); err != nil {
			return nil, err
		}
		items = append(items, path)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveDBVFSEntryTree = `-- name: MoveDBVFSEntryTree :exec
UPDATE vfs_db_entries
SET
    path = CAST(?1 AS TEXT) || substr(path, length(CAST(?2 AS TEXT)) + 1)
WHERE
    namespace = ?3
    AND (
        path = CAST(?2 AS TEXT)
        OR substr(path, 1, length(CAST(?4 AS TEXT))) = CAST(?4 AS TEXT)
    )
`

type MoveDBVFSEntryTreeParams struct {
	Dst       string
	Src       string
	Namespace string
	Prefix    string
}

// Renames src and every descendant of it to sit under dst.
func (q *Queries) MoveDBVFSEntryTree(ctx context.Context, arg MoveDBVFSEntryTreeParams) error {
	_, err := q.db.ExecContext(ctx, moveDBVFSEntryTree,
		arg.Dst,
		arg.Src,
		arg.Namespace,
		arg.Prefix,
	)
	return err
}

const upsertDBVFSFile = `-- name: UpsertDBVFSFile :execrows
INSERT INTO
    vfs_db_entries (namespace, path, is_dir, size, mime_type, content, updated_at)
VALUES
    (?, ?, 0, ?, ?, ?, datetime('now'))
ON CONFLICT (namespace, path) DO UPDATE SET
    size = excluded.size,
    mime_type = excluded.mime_type,
    content = excluded.content,
    updated_at = excluded.updated_at
WHERE
    is_dir = 0
`

type UpsertDBVFSFileParams struct {
	Namespace string
	Path      string
	Size      int64
	MimeType  string
	Content   []byte
}

// A directory already at the path is left alone and reports no rows.
func (q *Queries) UpsertDBVFSFile(ctx context.Context, arg UpsertDBVFSFileParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, upsertDBVFSFile,
		arg.Namespace,
		arg.Path,
		arg.Size,
		arg.MimeType,
		arg.Content,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertVFSMetadata = `-- name: UpsertVFSMetadata :exec
INSERT INTO
    vfs_metadata (namespace, path, key, value, updated_at)
VALUES
    (?, ?, ?, ?, datetime('now'))
ON CONFLICT (namespace, path, key) DO UPDATE SET
    value = excluded.value,
    updated_at = excluded.updated_at
`

type UpsertVFSMetadataParams struct {
	Namespace string
	Path      string
	Key       string
	Value     string
}

func (q *Queries) UpsertVFSMetadata(ctx context.Context, arg UpsertVFSMetadataParams) error {
	_, err := q.db.ExecContext(ctx, upsertVFSMetadata,
		arg.Namespace,
		arg.Path,
		arg.Key,
		arg.Value,
	)
	return err
}
