// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: video_jobs.sql

package db

import (
	"context"
)

const cancelVideoJob = `-- name: CancelVideoJob :exec
UPDATE video_jobs
SET status     = 'cancelled',
    updated_at = datetime('now')
WHERE id = ? AND status = 'pending'
`

func (q *Queries) CancelVideoJob(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, cancelVideoJob, id)
	return err
}

const createVideoJob = `-- name: CreateVideoJob :one
INSERT INTO video_jobs (job_type, device_serial, input_rel_path, output_rel_path, params)
VALUES (?, ?, ?, ?, ?)
RETURNING id
`

type CreateVideoJobParams struct {
	JobType       string
	DeviceSerial  string
	InputRelPath  string
	OutputRelPath string
	Params        string
}

func (q *Queries) CreateVideoJob(ctx context.Context, arg CreateVideoJobParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createVideoJob,
		arg.JobType,
		arg.DeviceSerial,
		arg.InputRelPath,
		arg.OutputRelPath,
		arg.Params,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getVideoJob = `-- name: GetVideoJob :one
SELECT id, job_type, status, device_serial, input_rel_path, output_rel_path, params, progress, error_message, created_at, updated_at FROM video_jobs WHERE id = ? LIMIT 1
`

func (q *Queries) GetVideoJob(ctx context.Context, id int64) (VideoJob, error) {
	row := q.db.QueryRowContext(ctx, getVideoJob, id)
	var i VideoJob
	err := row.Scan(
		&i.ID,
		&i.JobType,
		&i.Status,
		&i.DeviceSerial,
		&i.InputRelPath,
		&i.OutputRelPath,
		&i.Params,
		&i.Progress,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPendingVideoJobs = `-- name: ListPendingVideoJobs :many
SELECT id, job_type, status, device_serial, input_rel_path, output_rel_path, params, progress, error_message, created_at, updated_at FROM video_jobs
WHERE status = 'pending'
ORDER BY created_at ASC
LIMIT 10
`

func (q *Queries) ListPendingVideoJobs(ctx context.Context) ([]VideoJob, error) {
	rows, err := q.db.QueryContext(ctx, listPendingVideoJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VideoJob
	for rows.Next() {
		var i VideoJob
		if err := rows.Scan(
			&i.ID,
			&i.JobType,
			&i.Status,
			&i.DeviceSerial,
			&i.InputRelPath,
			&i.OutputRelPath,
			&i.Params,
			&i.Progress,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVideoJobs = `-- name: ListVideoJobs :many
SELECT id, job_type, status, device_serial, input_rel_path, output_rel_path, params, progress, error_message, created_at, updated_at FROM video_jobs
ORDER BY created_at DESC
LIMIT 50
`

func (q *Queries) ListVideoJobs(ctx context.Context) ([]VideoJob, error) {
	rows, err := q.db.QueryContext(ctx, listVideoJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VideoJob
	for rows.Next() {
		var i VideoJob
		if err := rows.Scan(
			&i.ID,
			&i.JobType,
			&i.Status,
			&i.DeviceSerial,
			&i.InputRelPath,
			&i.OutputRelPath,
			&i.Params,
			&i.Progress,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVideoJobStatus = `-- name: UpdateVideoJobStatus :exec
UPDATE video_jobs
SET status        = ?,
    progress      = ?,
    output_rel_path = ?,
    error_message = ?,
    updated_at    = datetime('now')
WHERE id = ?
`

type UpdateVideoJobStatusParams struct {
	Status        string
	Progress      float64
	OutputRelPath string
	ErrorMessage  string
	ID            int64
}

func (q *Queries) UpdateVideoJobStatus(ctx context.Context, arg UpdateVideoJobStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateVideoJobStatus,
		arg.Status,
		arg.Progress,
		arg.OutputRelPath,
		arg.ErrorMessage,
		arg.ID,
	)
	return err
}
